// ================= I18N (FR / EN) + THÈME =================
const TXT = {
  fr: {
    jours: "jours", pseudo: "Pseudo", kg: "kg",
    togglePintes: "🍺 Pintes", toggleKm: "🏔️ Km",
    objectif: "Objectif :", kmWeek: "km / semaine", equiv: "équivalent", joursCourus: "jours courus",
    equivNote: "Équivalences calculées pour {p} kg — change ton poids pour recalculer",
    defi: "🎯 Défi : {n} 🍺", defiOk: "— explosé ! 🎉", defiStart: "— lève-toi et va la chercher !", defiReste: "— encore {n} !",
    streakHome: "🔥 {n} jours de suite — ta série de courses consécutives (badges à 3 et 7 j)",
    prochainBadge: "Prochain badge", tousBadges: "🏆 Tous les badges débloqués !",
    record: "🏆 Record 12 mois :", recordSem: "semaine du", battu: " · 🎉 battu !",
    cta: "C'est parti ! 🏃", bilanBadges: "📊 Bilan & badges", brasseriesBtn: "🍺 Find my pub",
    defisBtn: "🏁 Challenge", defisTitre: "🏁 Challenge de groupe",
    pwaTitre: "📲 Installer l'app", pwaBtn: "Installer Beer Runner", pwaInstalle: "✅ App installée !",
    pwaInfo: "Menu Chrome (⋮) → « Ajouter à l'écran d'accueil » — l'app s'ouvrira plein écran, comme une vraie app 🍺",
    notifMer: "Mercredi ! Une petite course aujourd'hui = bière du week-end méritée 🍺", notifBiereMer: "La bière du jour : {n} — viens la découvrir !", notifVen: "Vendredi soir ! Dernières heures pour remplir ton fût avant l'apéro 🍺", notifBiereVen: "La bière du jour : {n} — à déguster bien méritée !",
    biereJour: "🍺 La bière du jour",
    futTitre: "Pintes à boire sans culpabilité", futExpire: "Déjà payées par tes courses 🍺 Mais bois vite : −50 % par jour, tout fond après 3 jours.",
    welcomeTitre: "🍺 Bienvenue sur Beer Runner !",
    welcomeIntro: "Cours, brûle des kcal, transforme-les en pintes. Ici, chaque bière se mérite.",
    welcomeAccueil: "🏃 Cours → ton fût se remplit (258 kcal ≈ 1 pinte)",
    welcomeRun: "⏳ Ton fût se vide tout seul : demi-vie de 24 h",
    welcomeBtn: "C'est parti ! 🍺",
    gueuleBadge: "🍺 Gueule de bois : gains −12 % (conso < 12 h)",
    soberBadge: "🌱 Sobre {d} j : gains +{p} %",
    defisDesc: "Course entre potes — le classement vit ici, l'animation vit dans WhatsApp 😄",
    defiNom: "Nom du défi :", defiNomPh: "Les Mousquetaires de la Mousse…",
    defiObj: "Objectif (pintes cette semaine) :", defiCreer: "💪 Lancer le défi",
    defiCodeLbl: "Code du fût :", defiRejoindre: "Rejoindre par code",
    defiCodePh: "MOUSSE-42", defiInvalide: "Code invalide",
    defiWAInvite: "📲 Inviter par WhatsApp",
    defiWAMsg: "🍺 Rejoins mon défi Beer Runner ! *{n}* — objectif : {o} pintes éliminées cette semaine. Ouvre l'app, onglet 🏁 Défi de groupe, colle le code {c}. Que le meilleur fût gagne ! 🏃🔥",
    defiPublier: "📋 Publier mon score", defiScoreCopie: "Score copié !",
    defiScoreMsg: "🍺 Beer Runner · {n}\n👤 {p}\n🔥 {b} pintes éliminées · {k} km cette semaine\n🏅 {t} badges",
    defiCollerLbl: "Coller les scores du groupe :", defiCollerPh: "Colle ici les messages des potes…",
    defiClasse: "Classer !", defiPodium: "🏆 Podion", defiPersonnel: "toi",
    defiQuit: "Quitter le défi", defiAucun: "Aucun défi en cours — lance-en un ou rejoins un code !",
    home: "← Accueil", homeBtn: "Accueil", pintes: "pintes", kg: "kg",
    brasseriesContact: "🍺 Brasserie ? Devenez le fût officiel de Beer Runner",
    temps: "TEMPS", vitesse: "⚡ Vitesse :", distanceTxt: "📏 Distance :", pintePourToi: "🍺 1 pinte = {k} km pour toi",
    tempsPinte: "⏱️ Temps pour éliminer 1 pinte :", calcule: "cours pour calculer…",
    pause: "⏸ Pause", reprendre: "Reprendre", courir: "Courir", terminerBtn: "↺ Terminer",
    extra: " (+{n} extra !)", bonus: "Pinte bonus n°{n} !", bonusDesc: "Tu dépasses ton objectif — {n} pintes éliminées !",
    gpsNo: "📡 GPS non dispo → simulation 🎮", gpsSeek: "📡 Recherche du signal GPS…",
    boltMsg: "🚀 44,7 km/h atteints ! Soit vous êtes champion du monde 🏆, soit vous êtes dans un moyen de transport 😅",

    regle10: "⏳ Règle des 10 min : ton corps a besoin d'au moins 10 minutes d'effort avant de puiser dans les réserves — avant ça, rien d'éliminé. Bonus : la distance courue pendant l'échauffement compte quand même !",
    gpsOk: "📡 GPS actif — cours !", gpsRefus: "📡 GPS refusé → simulation 🎮",
    gpsDenied: "📍 Position refusée. Active-la : app Beer Runner (appui long) → Infos appli → Autorisations → Position",
    badgeUnlock: "BADGE DÉBLOQUÉ !", copie: "Copié !", copieDesc: "Bilan copié — pense au #BeerRunner 😉",
    bilanTitre: "📊 Bilan de la semaine", partager: "📤 Partager",
    pintes: "pintes", pinte: "pinte", pintesTotal: "pintes éliminées au total", palier: "prochain palier :",
    eliminees: "🍺 ÉLIMINÉES", kcalElim: "🔥 KCAL ÉLIM.", trendTitre: "📈 Tendance · 12 semaines", trendNow: "act.", trendTotal: "Total 12 semaines :", badgesTitre: "🎖️ Tous les badges", badgesObtenus: "obtenus", hausse: "📈 En hausse", baisse: "📉 En baisse", stable: "➖ Stable",
    vsDerniere: "vs semaine dernière ({p} 🍺) :", serie: "Série : {n} j 🔥",
    aucune: "Aucune course cette semaine… ta pinte t'attend ! 🍺🏃",
    trophees: "🏅 Trophées ({n}/{t})",
    bravo: "BRAVO !", objAtteint: "Objectif atteint :", enTime: "en",
    pinteNr: "Pinte n°{n} éliminée !",
    totalLine: "Total : {p} pintes · Niveau : {e} {n} · Série : {s} j 🔥",
    continuer: "Continuer 🏃", terminer: "Terminer",
    brasseriesTitre: "🍺 Find my pub",
    brasseriesDesc: "Trouve où célébrer tes pintes éliminées — les micro-brasseries autour de tes parcours de course.",
    locateMe: "Me localiser", locating: "Localisation…", reSituer: "Position actualisée ✓ (re-situer)",
    ouVille: "ou ville :", maPos: "ma position",
    posOk: "✓ Position trouvée — les résultats s'ouvrent dans Maps autour de toi",
    posErr: "Position indisponible — indique ta ville ci-dessus, ça marche pareil !",
    posDenied: "📍 Position refusée — active-la : app Beer Runner (appui long) → Infos appli → Autorisations → Position",
    ouvrirMaps: "Ouvrir dans Maps →",
    astuce: "Astuce : la carte s'ouvre centrée sur ta position de course — parfait pour repérer la brasserie à 500 m de ton point d'arrivée. Santé ! 🍻",
    total: "total",
    shareTxt: "🍻 Beer Runner™ — {d}\nCette semaine : {km} km = {p} pintes éliminées !\nTotal : {tp} pintes · Niveau {n}\n{b} badges 🏅\n#BeerRunner #CourirPourBoire → beerrunner.app",
  },
  en: {
    jours: "days", pseudo: "Nickname", kg: "kg",
    togglePintes: "🍺 Pints", toggleKm: "🏔️ Km",
    objectif: "Goal:", kmWeek: "km / week", equiv: "equivalent", joursCourus: "days run",
    equivNote: "Equivalents calculated for {p} kg — change your weight to recalculate",
    defi: "🎯 Challenge: {n} 🍺", defiOk: "— smashed! 🎉", defiStart: "— get up and go get it!", defiReste: "— {n} to go!",
    streakHome: "🔥 {n} days in a row — your consecutive-run streak (badges at 3 and 7 d)",
    prochainBadge: "Next badge", tousBadges: "🏆 All badges unlocked!",
    record: "🏆 12-month record:", recordSem: "week of", battu: " · 🎉 beaten!",
    cta: "Let's go! 🏃", bilanBadges: "📊 Summary & badges", brasseriesBtn: "🍺 Find my pub",
    defisBtn: "🏁 Challenge", defisTitre: "🏁 Group challenge",
    pwaTitre: "📲 Install the app", pwaBtn: "Install Beer Runner", pwaInstalle: "✅ App installed!",
    pwaInfo: "Chrome menu (⋮) → 'Add to Home screen' — the app will open full-screen, like a real app 🍺",
    notifMer: "Wednesday! A little run today = weekend beer earned 🍺", notifBiereMer: "Beer of the day: {n} — come check it out!", notifVen: "Friday night! Last hours to fill your keg before drinks 🍺", notifBiereVen: "Beer of the day: {n} — enjoy it well earned!",
    biereJour: "🍺 Beer of the day",
    futTitre: "Guilt-free pints", futExpire: "Already paid for by your runs 🍺 But drink fast: −50% per day, all melts after 3 days.",
    welcomeTitre: "🍺 Welcome to Beer Runner!",
    welcomeIntro: "Run, burn kcal, turn them into pints. Here, every beer is earned.",
    welcomeAccueil: "🏃 Run → your keg fills up (258 kcal ≈ 1 pint)",
    welcomeRun: "⏳ Your keg drains on its own: 24h half-life",
    welcomeBtn: "Let's go! 🍺",
    gueuleBadge: "🍺 Hangover: gains −12% (drank < 12h ago)",
    soberBadge: "🌱 Sober {d} d: gains +{p}%",
    defisDesc: "Run with friends — the leaderboard lives here, the banter lives on WhatsApp 😄",
    defiNom: "Challenge name:", defiNomPh: "The Musketeers of Foam…",
    defiObj: "Goal (pints this week):", defiCreer: "💪 Start the challenge",
    defiCodeLbl: "Keg code:", defiRejoindre: "Join with a code",
    defiCodePh: "FOAM-42", defiInvalide: "Invalid code",
    defiWAInvite: "📲 Invite on WhatsApp",
    defiWAMsg: "🍺 Join my Beer Runner challenge! *{n}* — goal: {o} pints burned this week. Open the app, 🏁 Group challenge tab, paste code {c}. May the best keg win! 🏃🔥",
    defiPublier: "📋 Post my score", defiScoreCopie: "Score copied!",
    defiScoreMsg: "🍺 Beer Runner · {n}\n👤 {p}\n🔥 {b} pints burned · {k} km this week\n🏅 {t} badges",
    defiCollerLbl: "Paste the group's scores:", defiCollerPh: "Paste your friends' messages here…",
    defiClasse: "Rank!", defiPodium: "🏆 Podium", defiPersonnel: "you",
    defiQuit: "Leave challenge", defiAucun: "No challenge yet — start one or join a code!",
    home: "← Home", homeBtn: "Home", pintes: "pints", kg: "kg",
    brasseriesContact: "🍺 Brewery? Become Beer Runner's official keg",
    temps: "TIME", vitesse: "⚡ Speed:", distanceTxt: "📏 Distance:", pintePourToi: "🍺 1 pint = {k} km for you",
    tempsPinte: "⏱️ Time to burn 1 pint:", calcule: "run to calculate…",
    pause: "⏸ Pause", reprendre: "Resume", courir: "Run", terminerBtn: "↺ Finish",
    extra: " (+{n} extra!)", bonus: "Bonus pint n°{n}!", bonusDesc: "You're past your goal — {n} pints burned!",
    gpsNo: "📡 No GPS → simulation 🎮", gpsSeek: "📡 Looking for GPS signal…",
    boltMsg: "🚀 44.7 km/h reached! Either you're a world champion 🏆, or you're in a vehicle 😅",

    regle10: "⏳ The 10-min rule: your body needs at least 10 minutes of effort before tapping into reserves — before that, nothing burned. Bonus: distance run during warm-up still counts!",
    gpsOk: "📡 GPS active — run!", gpsRefus: "📡 GPS denied → simulation 🎮",
    gpsDenied: "📍 Location denied. Enable it: Beer Runner app (long press) → App info → Permissions → Location",
    badgeUnlock: "BADGE UNLOCKED!", copie: "Copied!", copieDesc: "Summary copied — think #BeerRunner 😉",
    bilanTitre: "📊 Weekly summary", partager: "📤 Share",
    pintes: "pints", pinte: "pint", pintesTotal: "pints burned in total", palier: "next tier:",
    eliminees: "🍺 BURNED", kcalElim: "🔥 KCAL BURNED", trendTitre: "📈 Trend · 12 weeks", trendNow: "now", trendTotal: "12-week total:", badgesTitre: "🎖️ All badges", badgesObtenus: "earned", hausse: "📈 Up", baisse: "📉 Down", stable: "➖ Steady",
    vsDerniere: "vs last week ({p} 🍺):", serie: "Streak: {n} d 🔥",
    aucune: "No runs this week… your pint is waiting! 🍺🏃",
    trophees: "🏅 Trophies ({n}/{t})",
    bravo: "CHEERS !", objAtteint: "Goal reached:", enTime: "in",
    pinteNr: "Pint n°{n} burned!",
    totalLine: "Total: {p} pints · Level: {e} {n} · Streak: {s} d 🔥",
    continuer: "Keep going 🏃", terminer: "Finish",
    brasseriesTitre: "🍺 Find my pub",
    brasseriesDesc: "Find where to celebrate your burned pints — the microbreweries around your running routes.",
    locateMe: "Locate me", locating: "Locating…", reSituer: "Position found ✓ (refresh)",
    ouVille: "or city:", maPos: "my location",
    posOk: "✓ Position found — results open in Maps around you",
    posErr: "Position unavailable — enter your city above, works the same!",
    posDenied: "📍 Location denied — enable it: Beer Runner app (long press) → App info → Permissions → Location",
    ouvrirMaps: "Open in Maps →",
    astuce: "Tip: the map opens centered on your running position — perfect to spot the brewery 500 m from your finish line. Cheers! 🍻",
    total: "total",
    shareTxt: "🍻 Beer Runner™ — {d}\nThis week: {km} km = {p} pints burned!\nTotal: {tp} pints · Level {n}\n{b} badges 🏅\n#BeerRunner #RunToDrink → beerrunner.app",
  },
};
const t = (k, p, lg) => {
  const lang = lg || L();
  let s = (TXT[lang] && TXT[lang][k]) || TXT.fr[k] || k;
  if (p) for (const key in p) s = s.split("{" + key + "}").join(String(p[key]));
  return s;
};
// ---------- traductions niveaux & badges ----------
const NIVEAUX_EN = ["Thirsty", "Brewer Apprentice", "Pint Runner", "Bar Regular", "Keg Master", "Pub Legend", "Trail-Brewing Myth", "Foam Emperor", "Hops Deity"];
const nName = (nv, lg) => ((lg || L()) === "en" ? NIVEAUX_EN[NIVEAUX.findIndex((n) => n.min === nv.min)] || nv.nom : nv.nom);
const BADGES_EN = {
  first_run: ["First Head", "Finish your 1st run"],
  first_pint: ["First Crash", "Burn 1 pint in total"],
  oktoberfest: ["Oktoberfest", "14 pints in one week (Munich's Big Mass)"],
  pintskeller: ["Pints Keller Dublin", "7 pints in one week (Irish spirit)"],
  cantillon: ["Cantillon Brussels", "21 pints in one week (the Brussels one)"],
  week3: ["Apero Athlete", "3 pints in one week"],
  perfect_week: ["The Trappist Week", "Run 3 days this week"],
  streak3: ["Beer-Run Habit", "3 days in a row"],
  streak7: ["Flemish Week", "7 days in a row (like brewing monks)"],
  streak30: ["Trappist Monk", "30 days in a row (patience & hops)"],
  run5: ["The Small Half", "5 km in one run"],
  run10: ["Kölsch of Cologne", "10 km in one run"],
  run15: ["Keg Rider", "15 km in one run"],
  run20: ["Hop Eagle", "20 km in one run"],
  run25: ["Foam Spitter", "25 km in one run"],
  run30: ["Brewing Bull", "30 km in one run"],
  semi: ["The Half-Crash", "21.1 km in one go (half)"],
  marathon: ["MARATHONER!", "42.2 km in one go"],
  ultra: ["Ultra-Pint", "60 km in one go"],
  run4h: ["Keg Forcer", "2h running in one go"],
  km10: ["Ten Markers", "10 km in total"],
  km42: ["Oktoberfest Road", "42.2 km in total"],
  km100: ["Centurion", "100 km in total"],
  km250: ["The Brewers' Road", "250 km in total"],
  km500: ["Around the Hop World", "500 km in total"],
  km1000: ["A Thousand Kays!", "1000 km in total"],
  pints10: ["The Ten", "10 pints in total"],
  pints50: ["The Bavarian Fifty", "50 pints in total"],
  pints100: ["The Golden Keg", "100 pints in total"],
  pints365: ["The Vintage", "365 pints in total"],
  triple: ["Triple Service", "3 pints in one run"],
  sixpack: ["Six-Pack (of beers!)", "6 pints in one run"],
  keg: ["Keg Piercer", "10 pints in one run"],
  brewery: ["Buy the Brewery", "20 pints in one run"],
  hour: ["The Beer Hour", "1h running in total"],
  hours10: ["Ten Hours at the Bar", "10h running in total"],
  hours24: ["Keg Day", "24h running in total"],
};
const bn = (b, lg) => ((lg || L()) === "en" && BADGES_EN[b.id] ? BADGES_EN[b.id][0] : b.nom);
const bd = (b, lg) => ((lg || L()) === "en" && BADGES_EN[b.id] ? BADGES_EN[b.id][1] : b.desc);
// difficulté progressive 1→37 : les premières courses débloquent vite, la fin = grind de légende
const ORDRE_DIFF = {
  first_run: 1, first_pint: 2, week3: 3, km10: 4, hour: 5, streak3: 6,
  pints10: 7, run5: 8, hours10: 9, run10: 10, km42: 11, pintskeller: 12,
  perfect_week: 13, triple: 14, streak7: 15, run15: 16, km100: 17, hours24: 18,
  sixpack: 19, semi: 20, run20: 21, km250: 22, pints50: 23, run25: 24,
  oktoberfest: 25, keg: 26, run30: 27, km500: 28, pints100: 29, run4h: 30,
  brewery: 31, km1000: 32, marathon: 33, pints365: 34, cantillon: 35, ultra: 36,
  streak30: 37,
};
// ---------- thème : fond sombre + texte clair (style d'origine) ----------
function ThemeCss() {
  return null;
}
// ================= COMPOSANTS UI =================
