
// Beer Runner — catalogue des 362 bières + traductions anglaises
// ---- Beer Runner — bières cultes, partie 1/5 du catalogue ----
const BIERES_CULTES_A = [
  { nom: "Petit Orval", emoji: "🐟", type: "Trappiste de table", origine: "Belgique — abbaye d'Orval", force: "4,5%", fa: "Le petit Orval, servi uniquement à l'auberge de l'abbaye : les moines le réservent aux pèlerins de passage." },
  { nom: "Westvleteren 12", emoji: "⛪", type: "Trappiste quadrupel", origine: "Belgique — Westvleteren", force: "10,2%", fa: "Brassée par des moines sans étiquette : pour l'acheter, rendez-vous à l'abbaye." },
  { nom: "Westvleteren Blond", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Westvleteren", force: "5,8%", fa: "La petite des moines, en vente uniquement à la porte du monastère." },
  { nom: "Westvleteren 8", emoji: "⛪", type: "Trappiste brune", origine: "Belgique — Westvleteren", force: "8%", fa: "Une des trois Westvleteren, aussi rare que ses soeurs." },
  { nom: "Orval", emoji: "🐟", type: "Trappiste unique", origine: "Belgique — abbaye d'Orval", force: "6,2%", fa: "Une truite aurait rendu un anneau perdu à la fontaine de l'abbaye : elle est sur l'étiquette." },
  { nom: "Rochefort 6", emoji: "🔢", type: "Trappiste dubbel", origine: "Belgique — Rochefort", force: "7,5%", fa: "La plus discrète des trois Rochefort, favorite des connaisseurs." },
  { nom: "Rochefort 8", emoji: "🔢", type: "Trappiste dubbel", origine: "Belgique — Rochefort", force: "9,2%", fa: "L'équilibre parfait entre la 6 et la 10, disent les moines." },
  { nom: "Rochefort 10", emoji: "🔢", type: "Trappiste quadrupel", origine: "Belgique — Rochefort", force: "11,3%", fa: "Les chiffres viennent des densités d'avant-guerre. La 10 se sirote comme un whisky." },
  { nom: "Rochefort Triple Extra", emoji: "🔢", type: "Trappiste triple", origine: "Belgique — Rochefort", force: "8,7%", fa: "Édition limitée des moines : quand elle est là, on se jette dessus." },
  { nom: "Chimay Bleue", emoji: "⛪", type: "Trappiste strong ale", origine: "Belgique — Scourmont", force: "9%", fa: "La Grande Réserve : corsée, épicée, taillée pour vieillir en cave." },
  { nom: "Chimay Rouge", emoji: "⛪", type: "Trappiste dubbel", origine: "Belgique — Scourmont", force: "7%", fa: "La première Chimay de l'histoire, douce et fruitée." },
  { nom: "Chimay Blanche", emoji: "⛪", type: "Trappiste triple", origine: "Belgique — Scourmont", force: "8%", fa: "La « Cinq Cents » : amertume nette, muscat en finale." },
  { nom: "Chimay Dorée", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Scourmont", force: "4,8%", fa: "Pendant des décennies, elle était réservée aux moines et à leurs invités." },
  { nom: "Westmalle Tripel", emoji: "⛪", type: "Trappiste triple", origine: "Belgique — Westmalle", force: "9,5%", fa: "LA triple de référence : le monde entier essaie de la copier." },
  { nom: "Westmalle Dubbel", emoji: "⛪", type: "Trappiste dubbel", origine: "Belgique — Westmalle", force: "7%", fa: "La dubbel mère : elle a fixé le style des brunes d'abbaye." },
  { nom: "Westmalle Extra", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Westmalle", force: "4,8%", fa: "La bière de table des moines eux-mêmes, introuvable en magasin." },
  { nom: "Achel Blond", emoji: "⛪", type: "Trappiste blonde", origine: "Belgique — Hamont-Achel", force: "8%", fa: "Brassée à la frontière néerlandaise dans la plus discrète des abbayes trappistes." },
  { nom: "Achel Bruin", emoji: "⛪", type: "Trappiste brune", origine: "Belgique — Hamont-Achel", force: "8,5%", fa: "Brune de garde, avec un léger goût de caramel grillé." },
  { nom: "Leffe Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Dinant", force: "6,6%", fa: "Née à l'abbaye de Leffe en 1152 : les moines brassaient pour financer l'entretien." },
  { nom: "Leffe Brune", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Dinant", force: "6,5%", fa: "Douce et torréfiée, la brune du dimanche après-midi." },
  { nom: "Leffe Rituel 9°", emoji: "🇧🇪", type: "Abbaye forte", origine: "Belgique — Dinant", force: "9%", fa: "Une Leffe qui monte : à siroter lentement, pas à gorgées." },
  { nom: "Grimbergen Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Grimbergen", force: "6%", fa: "Le phénix sur l'étiquette : l'abbaye a brûlé et rebâti plein de fois." },
  { nom: "Grimbergen Optimo Bruno", emoji: "🇧🇪", type: "Abbaye forte", origine: "Belgique — Grimbergen", force: "10%", fa: "La « bière des érudits » de Grimbergen, tonneau d'excellence." },
  { nom: "Maredsous 8", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Maredsous", force: "8%", fa: "Brune de l'abbaye bénédictine, parfaite avec un fromage du même nom." },
  { nom: "Maredsous 10", emoji: "🇧🇪", type: "Abbaye quadrupel", origine: "Belgique — Maredsous", force: "10%", fa: "La corpsé de la famille, à partager à deux… ou pas." },
  { nom: "St Bernardus Abt 12", emoji: "🇧🇪", type: "Abbaye quadrupel", origine: "Belgique — Watou", force: "10%", fa: "Brassée jadis pour les moines de Westvleteren : la cousine laïque de la 12." },
  { nom: "St Bernardus Wit", emoji: "🇧🇪", type: "Blanche d'abbaye", origine: "Belgique — Watou", force: "5,5%", fa: "Blanche crémeuse d'inspiration traditionnelle, citron facultatif." },
  { nom: "St Bernardus Christmas Ale", emoji: "🇧🇪", type: "Abbaye de Noël", origine: "Belgique — Watou", force: "10%", fa: "La bière de l'Avent flamand : épices, dattes, et un bon feu de cheminée." },
  { nom: "St Bernardus Grottenbier", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Watou", force: "6,5%", fa: "Conçue pour vieillir dans les grottes de marbre de la région." },
  { nom: "Affligem Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Affligem", force: "6,8%", fa: "Bière d'abbaye millénaire : la mousse est digne d'un cappuccino." },
  { nom: "Affligem Tripel", emoji: "🇧🇪", type: "Abbaye triple", origine: "Belgique — Affligem", force: "9,5%", fa: "Triple de haut vol, héritée des moines d'Affligem." },
  { nom: "Val-Dieu Triple", emoji: "🇧🇪", type: "Abbaye triple", origine: "Belgique — Aubel", force: "9%", fa: "L'abbaye du Val-Dieu a rouvert sa brasserie en l'an 2000." },
  { nom: "Val-Dieu Brune", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Aubel", force: "8%", fa: "Brune de garde brassée avec l'eau de la source de l'abbaye." },
  { nom: "Tongerlo Tripel", emoji: "🇧🇪", type: "Abbaye triple", origine: "Belgique — Tongerlo", force: "8%", fa: "Une triple de la plus ancienne abbaye de chanoines du pays." },
  { nom: "Floreffe Blonde", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Floreffe", force: "6,3%", fa: "Les chanoines de Floreffe brassaient déjà au XIIe siècle." },
  { nom: "Postel Blond", emoji: "🇧🇪", type: "Abbaye blonde", origine: "Belgique — Postel", force: "7%", fa: "Le goût rond des moines de la forêt de Postel." },
  { nom: "Bornem Double", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Bornem", force: "6,5%", fa: "Brune de l'abbaye de Bornem, dans le style des anciennes bières de jeûne." },
  { nom: "Ename Dubbel", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Ename", force: "7%", fa: "Une brune de l'abbaye disparue d'Ename, ressuscitée par brasserie." },
  { nom: "Saint-Feuillien Brune", emoji: "🇧🇪", type: "Abbaye brune", origine: "Belgique — Le Roeulx", force: "8,5%", fa: "L'abbaye de Saint-Feuillien brasse depuis 1873 en pays de Hainaut." },
  { nom: "Steenbrugge Dubbel", emoji: "🇧🇪", type: "Abbaye dubbel", origine: "Belgique — Bruges", force: "6,5%", fa: "Brune de l'abbaye Saint-Pierre de Steenbrugge, recette des moines." },
  { nom: "Duvel", emoji: "😈", type: "Strong pale ale", origine: "Belgique — Puurs", force: "8,5%", fa: "Un brasseur a goûté le premier essai : « c'est un vrai Duvel ! » — un vrai démon." },
  { nom: "Duvel Tripel Hop", emoji: "😈", type: "Strong pale ale", origine: "Belgique — Puurs", force: "9,5%", fa: "Trois houblons frais au lieu d'un : la version pentathlon du Démon." },
  { nom: "Chouffe", emoji: "🧙", type: "Strong golden ale", origine: "Belgique — Achouffe", force: "8%", fa: "Le gnome à barbe blanche protège la brasserie… et pique des bières aux touristes." },
  { nom: "La Chouffe Mc Chouffe", emoji: "🧌", type: "Scotch ale belge", origine: "Belgique — Achouffe", force: "8%", fa: "Une scotch brassée par des Belges avec un nain écossais sur l'étiquette." },
  { nom: "N'Ice Chouffe", emoji: "🇧🇪", type: "Bière de Noël", origine: "Belgique — Achouffe", force: "10%", fa: "La Chouffe d'hiver : épices et quetsches, le bonnet du gnome en plus." },
  { nom: "Delirium Tremens", emoji: "🇧🇪", type: "Strong pale ale", origine: "Belgique — Melle", force: "8,5%", fa: "L'éléphant rose sur la bouteille : ici, le délire est dans le nom." },
  { nom: "Delirium Noël", emoji: "🇧🇪", type: "Bière de Noël", origine: "Belgique — Melle", force: "8%", fa: "La version de fête du délire : à consommer avant de voir des rennes roses." },
  { nom: "Piraat", emoji: "🏴‍☠️", type: "Strong pale ale", origine: "Belgique — Wuustwezel", force: "10,5%", fa: "10,5% de houblon corsé : le pavillon noir des bières belges." },
  { nom: "Gulden Draak", emoji: "🐉", type: "Strong dark ale", origine: "Belgique — Ertvelde", force: "10,5%", fa: "Le dragon doré : une triple fermentation en bouteille, un monstre de garde." },
  { nom: "Kasteel Rouge", emoji: "🇧🇪", type: "Bière cerise-guimauve", origine: "Belgique — Ingelmunster", force: "8%", fa: "Brune macérée aux cerises : le dessert qui se boit." },
  { nom: "Kasteel Donker", emoji: "🇧🇪", type: "Strong dark ale", origine: "Belgique — Ingelmunster", force: "11%", fa: "La brune du château d'Ingelmunster, douce comme un sirop d'orge." },
  { nom: "Ciney Blonde", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Ciney", force: "7%", fa: "La blonde de Ciney, à la mousse généreuse et à l'amertume polie." },
  { nom: "Ciney Brune", emoji: "🇧🇪", type: "Strong brune", origine: "Belgique — Ciney", force: "7,5%", fa: "La brune du Condroz, crème de caramel et d'orge." },
  { nom: "Brigand", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Oostkamp", force: "9%", fa: "Nommée d'après les rebelles de 1798 : elle mène sa propre révolte." },
  { nom: "Lucifer", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Verhaeghe", force: "8%", fa: "Le nom dit tout : dorée, diablement épicée, damnation garantie." },
  { nom: "Judas", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Alken", force: "8,5%", fa: "Un baiser et une gifle : douceur d'abord, alcool ensuite." },
  { nom: "Gouden Carolus Classic", emoji: "🇧🇪", type: "Strong dark ale", origine: "Belgique — Mechelen", force: "8,5%", fa: "La bière de l'empereur Charles Quint, disent les brasseurs de Malines." },
  { nom: "Gouden Carolus Hopsinjoor", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Mechelen", force: "8,5%", fa: "Neuf houblons différents : la couronne se porte aussi sur la langue." },
  { nom: "Bush Ambrée", emoji: "🇧🇪", type: "Strong amber ale", origine: "Belgique — Péruwelz", force: "12%", fa: "La plus forte des bières belges classiques : à respecter, pas à defier." },
  { nom: "Barbar", emoji: "🍯", type: "Bière au miel", origine: "Belgique — Quenast", force: "8%", fa: "Une blonde au miel d'acacia : l'abeille fait la moitié du travail." },
  { nom: "Verboden Vrucht", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Wieze", force: "8,8%", fa: "Le fruit défendu : Adam et Ève sur l'étiquette, le péché dans le verre." },
  { nom: "Cuvée des Trolls", emoji: "🇧🇪", type: "Strong golden ale", origine: "Belgique — Dottignies", force: "7%", fa: "Brassée avec des oranges séchées : la bouche pleine et la tête légère." },
  { nom: "Satan Gold", emoji: "🇧🇪", type: "Strong blonde", origine: "Belgique — Igoulême", force: "8%", fa: "Une « bière des Dieux » : le marketing était déjà fort en 1988." },
  { nom: "Tripel Karmeliet", emoji: "🍺", type: "Triple aux trois céréales", origine: "Belgique — Buggenhout", force: "7,8%", fa: "Orge, froment ET avoine : la triple aux trois céréales, un délice croustillant." },
  { nom: "Straffe Hendrik", emoji: "🇧🇪", type: "Strong quadrupel", origine: "Belgique — Bruges", force: "9%", fa: "La « forte Henri » de la famille Van Houcke, à Bruges-médiévale." },
  { nom: "Brugse Zot Dubbel", emoji: "🇧🇪", type: "Dubbel brugeoise", origine: "Belgique — Bruges", force: "6%", fa: "Les « fous de Bruges » raillés par l'empereur Maximilien : le surnom est resté." },
  { nom: "Kwak", emoji: "🎻", type: "Strong amber ale", origine: "Belgique — Buggenhout", force: "8%", fa: "Le verre en forme de mousqueton s'attache au banc des cochers. Attache-toi." },
  { nom: "Poperings Hommelbier", emoji: "🇧🇪", type: "Bière au houblon", origine: "Belgique — Poperinge", force: "7%", fa: "Hommel = houblon en flamand : la capitale du houblon belge se boit." },
  { nom: "Hommel Ale", emoji: "🇧🇪", type: "Bière au houblon", origine: "Belgique — Poperinge", force: "7%", fa: "Brassée par la famille Van Eecke, l'autre ferme-houblonnière du coin." },
  { nom: "Lupulus", emoji: "🇧🇪", type: "Bière au houblon", origine: "Belgique — Achouffe", force: "8,5%", fa: "Brassée à l'eau des sources ardennaises : le houblon y est roi." },
  { nom: "Silly Saison", emoji: "🇧🇪", type: "Saison", origine: "Belgique — Silly", force: "5%", fa: "La saison des fermes du Hainaut, racontée par la brasserie de Silly." },
  { nom: "Saison Dupont", emoji: "🌾", type: "Saison", origine: "Belgique — Tourpes", force: "6,5%", fa: "La saison de référence mondiale, née pour désaltérer les moissons." },
  { nom: "Avec les Bons Vœux", emoji: "🇧🇪", type: "Saison forte", origine: "Belgique — Tourpes", force: "9,5%", fa: "La saison premium des Dupont : la carte de voeux se boit." },
  { nom: "La Merveille", emoji: "🇧🇪", type: "Saison", origine: "Belgique — Bah-d'Écaussinnes", force: "6%", fa: "Saison de la ferme-brasserie de Blaugies, au bord du bocage." },
  { nom: "Fantôme", emoji: "🦆", type: "Saison fantaisiste", origine: "Belgique — Soy", force: "8%", fa: "Dany Prignon brasse des saisons imprévisibles : chaque fût est une surprise." },
  { nom: "Taras Boulba", emoji: "🌳", type: "Bière hoppy", origine: "Belgique — Bruxelles", force: "4,5%", fa: "Nabokov sur l'étiquette, du houblon frais dans le verre : 4,5% de poésie." },
  { nom: "Zinnebir", emoji: "🇧🇪", type: "Bière de Senne", origine: "Belgique — Bruxelles", force: "6%", fa: "La Senne, rivière bruxelloise, donne son nom à cette ambrée croquante." },
  { nom: "XX Bitter", emoji: "🇧🇪", type: "Bière ultra-amère", origine: "Belgique — Dottignies", force: "6,2%", fa: "De Ranke l'a faite pour les fanatiques d'amertume : âpre et fière." },
  { nom: "Guldenberg", emoji: "🇧🇪", type: "Blonde d'abbaye ambrée", origine: "Belgique — Dottignies", force: "8,5%", fa: "L'autre bijou de De Ranke : douce, dorée, houblonnée à l'ancienne." },
  { nom: "De Ranke Kriek", emoji: "🇧🇪", type: "Kriek traditionnelle", origine: "Belgique — Dottignies", force: "6%", fa: "Des vraies cerises sur lambic, sans sirop : l'acidité franche." },
  { nom: "Wipers Times", emoji: "🇧🇪", type: "Bière ambrée", origine: "Belgique — Dottignies", force: "6%", fa: "Hommage au journal des tranchées de la Grande Guerre, brassée à l'anglaise." },
  { nom: "Troubadour Mocha Stout", emoji: "🇧🇪", type: "Stout au café", origine: "Belgique — Roulers", force: "8,2%", fa: "Stout à la belge : cacao et café, sans oublier d'être ambrée-forte." },
  { nom: "Bourgogne des Flandres", emoji: "🇧🇪", type: "Rouge des Flandres", origine: "Belgique — Bruges", force: "5%", fa: "Assemblage de lambic et de brune douce : le vin de Bourgogne, version bière." },
  { nom: "Rodenbach", emoji: "🍒", type: "Rouge des Flandres", origine: "Belgique — Roulers", force: "5,2%", fa: "Vieillie deux ans en fûts de chêne : acidité et cerise, signature des Flandres." },
  { nom: "Rodenbach Vintage", emoji: "🍒", type: "Rouge des Flandres", origine: "Belgique — Roulers", force: "7%", fa: "Fût unique, millésimé : le grand cru des rouges flamandes." },
  { nom: "Duchesse de Bourgogne", emoji: "👑", type: "Rouge des Flandres", origine: "Belgique — Oudenaarde", force: "6,2%", fa: "Vieillie 18 mois en chêne : la duchse trône sur les tables fines." },
  { nom: "Liefmans Goudenband", emoji: "🇧🇪", type: "Rouge-brune de garde", origine: "Belgique — Oudenaarde", force: "8%", fa: "Coupée à l'ancienne au couteau, tellement elle est épaisse." },
  { nom: "Liefmans Cuvée Brut", emoji: "🇧🇪", type: "Kriek brut", origine: "Belgique — Oudenaarde", force: "6%", fa: "Macérée aux cerises à la façon du champagne : la bulle en plus." },
  { nom: "Cantillon Gueuze", emoji: "🇧🇪", type: "Gueuze assemblée", origine: "Belgique — Bruxelles", force: "5%", fa: "Fermentée par les levures sauvages de l'air de Bruxelles, dans un grenier ouvert." },
  { nom: "Cantillon Kriek", emoji: "🇧🇪", type: "Kriek sur lambic", origine: "Belgique — Bruxelles", force: "5%", fa: "Deux cents grammes de cerises par litre : le fruit et l'acidité en duel." },
  { nom: "Cantillon Rosé de Gambrinus", emoji: "🇧🇪", type: "Framboise sur lambic", origine: "Belgique — Bruxelles", force: "5%", fa: "La framboise noble sur lambic d'un an : rose et mordante." },
  { nom: "Cantillon Fou' Foune", emoji: "🍑", type: "Abricot sur lambic", origine: "Belgique — Bruxelles", force: "5%", fa: "Des abricots du Roussillon sur lambic : la fée électrique du brasseur." },
  { nom: "3 Fonteinen Oude Geuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Beersel", force: "6%", fa: "Assemblage de lambics d'un, deux et trois ans, en chruche de champagne." },
  { nom: "3 Fontainen Schaarbeekse Kriek", emoji: "🍒", type: "Kriek sauvage", origine: "Belgique — Beersel", force: "6,5%", fa: "Les petites cerises acides de Bruxelles, comme au bon vieux temps." },
  { nom: "Boon Oude Geuze Mariage Parfait", emoji: "🇧🇪", type: "Gueuze de garde", origine: "Belgique — Lembeek", force: "6,5%", fa: "Le « mariage parfait » : trois ans de fût avant la bouteille." },
  { nom: "Boon Kriek", emoji: "🇧🇪", type: "Kriek sur lambic", origine: "Belgique — Lembeek", force: "4,5%", fa: "La kriek douce-acide de la brasserie-musée de Lembeek." },
  { nom: "Lindemans Gueuze", emoji: "🇧🇪", type: "Gueuze douce", origine: "Belgique — Vlezenbeek", force: "4%", fa: "La gueuze filtrée et sucrée : la porte d'entrée du monde lambic." },
  { nom: "Lindemans Kriek", emoji: "🇧🇪", type: "Kriek douce", origine: "Belgique — Vlezenbeek", force: "4%", fa: "La kriex accessible : parfait pour convertir les sceptiques." },
  { nom: "Lindemans Framboise", emoji: "🇧🇪", type: "Framboise douce", origine: "Belgique — Vlezenbeek", force: "4%", fa: "Sirop de framboise ou pas, elle reste sur lambic véritable." },
  { nom: "Mort Subite Oude Gueuze", emoji: "⚡", type: "Gueuze traditionnelle", origine: "Belgique — Kobbegem", force: "5,5%", fa: "« Mort subite » : le nom du café de Bruxelles où on la buvait." },
  { nom: "Belle-Vue Gueuze", emoji: "🇧🇪", type: "Gueuze accessible", origine: "Belgique — Bruxelles", force: "5%", fa: "La gueuze du dimanche : douce, citronnée, à la mousse fine." },
  { nom: "Oud Beersel Oude Geuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Beersel", force: "6%", fa: "De la gueuze de comptoir, comme à l'école flamande." },
  { nom: "Tilquin Gueuze", emoji: "🇧🇪", type: "Gueuze d'assemblage", origine: "Belgique — Bierghes", force: "6,5%", fa: "Le dernier « blendeur » de gueuze indépendant : il achète le lambic, pas la brasserie." },
  { nom: "Hanssens Oude Gueuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Dworp", force: "6%", fa: "Une des plus acides du pays : les dents frémissent, le coeur aussi." },
  { nom: "Girardin Gueuze", emoji: "🇧🇪", type: "Gueuze traditionnelle", origine: "Belgique — Sint-Ulriks-Kapelle", force: "5%", fa: "La girafe de l'étiquette : une gueuze rustique du Brabant flamand." },
  { nom: "De Cam Oude Geuze", emoji: "🇧🇪", type: "Gueuze d'assemblage", origine: "Belgique — Gooik", force: "6%", fa: "Assemblée à la ferme, sur les hauts plateaux du Pajottenland." },
  { nom: "Hoegaarden", emoji: "🍋", type: "Blanche", origine: "Belgique — Hoegaarden", force: "4,9%", fa: "La blanche au coriandre et à l'écorce d'orange : inventée par Pierre Celis." },
  { nom: "Blanche de Namur", emoji: "🇧🇪", type: "Blanche", origine: "Belgique — Namur", force: "4,5%", fa: "Née de la légende de la « Blonde de Namur », princesse française du XVe." },
  { nom: "Brugs Tarwebier", emoji: "🇧🇪", type: "Blanche brugeoise", origine: "Belgique — Bruges", force: "4,6%", fa: "La « blé-bière » de Bruges : rafraîchissante après le Minnewater." },
  { nom: "Weihenstephaner", emoji: "🏰", type: "Hefeweizen", origine: "Allemagne — Freising", force: "5,4%", fa: "La plus ancienne brasserie du monde (1040) : elle a survécu à tout." },
  { nom: "Weihenstephaner Vitus", emoji: "🏰", type: "Weizenbock", origine: "Allemagne — Freising", force: "7,7%", fa: "Un doppelbock de froment : banane et clou de girofle dopés." },
  { nom: "Schneider Weisse Tap 6", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Kelheim", force: "5,4%", fa: "Georg Schneider garde le froment munichois vivant depuis 1872." },
  { nom: "Aventinus", emoji: "🇩🇪", type: "Weizen doppelbock", origine: "Allemagne — Kelheim", force: "8,2%", fa: "Le plus vieux doppelbock de froment de Bavière : complexe et velouté." },
  { nom: "Schneider Edel Weisse", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Kelheim", force: "6,2%", fa: "La version tonique et épicée du froment Schneider." },
  { nom: "Erdinger Weissbier", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Erding", force: "5,6%", fa: "La weissbier « du champion » : sport et bière, le contrat est signé." },
  { nom: "Franziskaner", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Munich", force: "5%", fa: "Le moine franciscain sur l'étiquette : le froment du centre de Munich." },
  { nom: "Maisel Weisse", emoji: "🇩🇪", type: "Weizen", origine: "Allemagne — Bayreuth", force: "7%", fa: "La « perle de Weisse » de Bayreuth : fruitée, charnue, généreuse." },
  { nom: "Ayinger Bräu Weisse", emoji: "🇩🇪", type: "Hefeweizen", origine: "Allemagne — Aying", force: "5,1%", fa: "Brassée dans le village d'Aying : la mousse est de la crème." },
  { nom: "Schöfferhofer Weizen", emoji: "🇩🇪", type: "Weizen", origine: "Allemagne — Mayence", force: "4,8%", fa: "Le froment de Mayence, celui qu'on trouve partout et qu'on reloue toujours." },
  { nom: "Augustiner Helles", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "5,2%", fa: "La favorite des Munichois : le robinet à bière tire à la verticale, pression par gravité." },
  { nom: "Augustiner Edelstoff", emoji: "🇩🇪", type: "Export helles", origine: "Allemagne — Munich", force: "5,6%", fa: "« Edelstoff » : le trésor de la brasserie des Augustins, en bouteille uniquement." },
];
