// ---- Beer Runner — bières cultes, partie 2/5 ----
const BIERES_CULTES_B = [
  { nom: "Augustiner Dunkel", emoji: "🇩🇪", type: "Dunkel", origine: "Allemagne — Munich", force: "5%", fa: "La brune de Munich par excellence : pain grillé et caramel." },
  { nom: "Tegernseer Spezial", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Tegernsee", force: "5,4%", fa: "La brasserie de l'ancienne abbaye de Tegernsee : le lac, les monts, la bière." },
  { nom: "Jever Pils", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Jever", force: "4,9%", fa: "La « pils au goût » du nord : sèche, herbacée, nette comme un vent de mer." },
  { nom: "Warsteiner", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Warstein", force: "4,8%", fa: "« La reine des pils » d'après la pub : la bombe allemande qu'on trouve partout." },
  { nom: "Radeberger", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Radeberger", force: "4,8%", fa: "La pils favorite des Allemands de l'Est, née sous Bismarck." },
  { nom: "Bitburger", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Bitburg", force: "4,8%", fa: "« Bitte ein Bit » : le slogan le plus reprenable d'Allemagne." },
  { nom: "Veltins", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Meschede", force: "4,8%", fa: "La pils du Sauerland, dans des bouteilles toujours très froides." },
  { nom: "Flensburger", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Flensbourg", force: "4,8%", fa: "Le clapot du bouchon à clapet (« plop ») : on l'entend avant de la boire." },
  { nom: "Rothaus Tannenzäpfle", emoji: "🌲", type: "Pilsner", origine: "Allemagne — Forêt-Noire", force: "5,1%", fa: "La « petite pomme de pin » de la Forêt-Noire : née dans une région de sapins." },
  { nom: "Kneitinger Pils", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Ratisbonne", force: "4,8%", fa: "La pils de Ratisbonne, la préférée des puristes bavarois." },
  { nom: "Hofbräu Original", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "5,5%", fa: "La brasserie du duc de Bavière : on y boit dans des chopes d'un litre." },
  { nom: "Löwenbräu Original", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "5,2%", fa: "Le lion de Munich brasse depuis 1383 : la bière de l'Oktoberfest." },
  { nom: "Paulaner Münchner Hell", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "4,9%", fa: "Les moines paulaniers brassaient pour survivre : leur helles est sainte." },
  { nom: "Paulaner Salvator", emoji: "🍺", type: "Doppelbock", origine: "Allemagne — Munich", force: "7,9%", fa: "Le « Sauveur » : les moines jeûnaient avec, d'où le nom. Sacrée excuse." },
  { nom: "Ayinger Celebrator", emoji: "🇩🇪", type: "Doppelbock", origine: "Allemagne — Aying", force: "6,7%", fa: "La médaille du bouc sur l'étiquette : le doppelbock de référence." },
  { nom: "Andechser Doppelbock", emoji: "⛪", type: "Doppelbock", origine: "Allemagne — Andechs", force: "7,1%", fa: "Brassée par les bénédictins de la colline d'Andechs : pèlerinage gustatif." },
  { nom: "Korbinian", emoji: "👑", type: "Doppelbock", origine: "Allemagne — Füssen", force: "9,2%", fa: "Nommée d'après saint Korbinian, l'évêque à l'ours : la légende et la bière." },
  { nom: "König Ludwig Weiss", emoji: "🇩🇪", type: "Weizen", origine: "Allemagne — Füssen", force: "5,5%", fa: "La brasserie royale de Hohenschwangau, face au château de Louis II." },
  { nom: "EKU 28", emoji: "🔥", type: "Doppelbock fort", origine: "Allemagne — Erlangen", force: "11%", fa: "Autrefois la bière la plus forte du monde : on la sirote comme un digestif." },
  { nom: "Kulmbacher Eisbock", emoji: "🧊", type: "Eisbock", origine: "Allemagne — Kulmbach", force: "9,2%", fa: "La légende : un tonneau oublié dehors, la glace enlevée, l'alcool concentré." },
  { nom: "Schneider Aventinus Eisbock", emoji: "🇩🇪", type: "Weizen eisbock", origine: "Allemagne — Kelheim", force: "12%", fa: "L'Aventinus congelé à mi-fermentation : banane, chocolat et Figuier du Brésil." },
  { nom: "Einbecker Mai-Ur-Bock", emoji: "🌱", type: "Bock de mai", origine: "Allemagne — Einbeck", force: "7%", fa: "Einbeck est la mère des bocks : son nom a donné « Bock » en bavarois." },
  { nom: "Schlenkerla Märzen", emoji: "🔥", type: "Rauchbier", origine: "Allemagne — Bamberg", force: "5,4%", fa: "Le malt fumé au bois de hêtre : le jambon de la bière, à Bamberg on adore." },
  { nom: "Schlenkerla Weizen", emoji: "🔥", type: "Rauchbier", origine: "Allemagne — Bamberg", force: "5,2%", fa: "Un froment fumé : la boulangerie et le comptoir dans le même verre." },
  { nom: "Spezial Rauchbier", emoji: "🔥", type: "Rauchbier", origine: "Allemagne — Bamberg", force: "5%", fa: "L'autre fumée de Bamberg, plus douce : la ville en compte deux écoles." },
  { nom: "Diebels Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Issum", force: "4,9%", fa: "La « voleuse » : l'alt de référence, rouge-brune et sèche." },
  { nom: "Uerige Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Düsseldorf", force: "4,3%", fa: "La brasserie d' « Uerige » le savoureux aigre : alt au comptoir, tournée minuscule." },
  { nom: "Schumacher Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Düsseldorf", force: "4,5%", fa: "La plus ancienne maison d'alt (1838) : on y boit debout, serrés, heureux." },
  { nom: "Füchschen Alt", emoji: "🇩🇪", type: "Altbier", origine: "Allemagne — Düsseldorf", force: "4,5%", fa: "Le petit renard du vieux Düsseldorf : amère et rustique." },
  { nom: "Gaffel Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "La kölsch de référence au chardon : tant que le verre est plein, on resserve." },
  { nom: "Reissdorf Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "La kölsch la plus bue de Cologne : 20 cl à la fois, à la folie douce." },
  { nom: "Früh Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "La kölsch du vieux-port, à côté de la cathédrale : un pèlerinage." },
  { nom: "Mühlen Kölsch", emoji: "🚂", type: "Kölsch", origine: "Allemagne — Cologne", force: "4,8%", fa: "Brassée au moulin de la ville : la plus confidentielle des kölsch." },
  { nom: "Berliner Kindl Weisse", emoji: "🍋", type: "Berliner Weisse", origine: "Allemagne — Berlin", force: "2,8%", fa: "La bière des rois de Prusse, si acide qu'on y ajoute un schuss de sirop." },
  { nom: "Pinkus Alt", emoji: "🇩🇪", type: "Altbier bio", origine: "Allemagne — Münster", force: "4,5%", fa: "La brasserie bio avant l'heure : le goût du vrai, depuis 1816." },
  { nom: "Weltenburger Barock Dunkel", emoji: "⛪", type: "Dunkel", origine: "Allemagne — Kelheim", force: "4,9%", fa: "L'abbaye revendique le titre de plus vieille brasserie de monastère du monde." },
  { nom: "Altbairisch Dunkel", emoji: "🇩🇪", type: "Dunkel", origine: "Allemagne — Aying", force: "5%", fa: "La brune de la vieille Bavière : pain de seigle, pruneau, douceur." },
  { nom: "Köstritzer Schwarzbier", emoji: "⚫", type: "Schwarzbier", origine: "Allemagne — Bad Köstritz", force: "4,8%", fa: "La noire de Goethe : le poète buvait ce « velours noir » à l'écriture." },
  { nom: "Goslarer Gose", emoji: "🌀", type: "Gose", origine: "Allemagne — Goslar", force: "4,5%", fa: "Acide, salée, coriandrée : la bière que le Moyen Âge a oubliée puis ressuscitée." },
  { nom: "Kuchlbauer Weisse", emoji: "🏰", type: "Weizen", origine: "Allemagne — Abensberg", force: "5,6%", fa: "Sa tour dorée a été dessinée par Hundertwasser : l'art avec la weissbier." },
  { nom: "Neumarkter Lammsbräu", emoji: "🌱", type: "Bio helles", origine: "Allemagne — Neumarkt", force: "5%", fa: "La pionnière bio allemande : la bière du respect, depuis 1979." },
  { nom: "Beck's", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Brême", force: "4,9%", fa: "La bouteille verte ne sort de Brême que pour l'export : en ville, on la boit en fût." },
  { nom: "St. Georgen Bräu Kellerbier", emoji: "🌾", type: "Kellerbier", origine: "Allemagne — Buttenheim", force: "4,9%", fa: "Brassée « sur lie » à l'ombre des caves : la bière de cave parfaite." },
  { nom: "Fischer Tradition", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Alsace, Strasbourg", force: "6%", fa: "La bière de garde : brassée l'hiver, gardée des mois pour tenir l'été. L'Alsace brassicole." },
  { nom: "Adelscott", emoji: "🇫🇷", type: "Bière fumée au malt whisky", origine: "France — Schiltigheim", force: "6,5%", fa: "Malt fumé au tourbe, façon whisky : l'Alsace en mode Écosse." },
  { nom: "Pelforth Blonde", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Lyon", force: "6,8%", fa: "« Pel mon dieu » : le pélican de Pelforth a conquis les bistrots français." },
  { nom: "Pelforth Brune", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Lyon", force: "6,6%", fa: "La brune des années 60 : les papas la réclament encore au comptoir." },
  { nom: "3 Monts", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Saint-Sylvestre", force: "8,5%", fa: "La gardienne du Nord : brassée dans les hauts de Flandre, taillée pour vieillir." },
  { nom: "La Goudale", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Douai", force: "7,2%", fa: "Conçue pour payer des « goudales » de dettes : la bière des comtes de Flandre." },
  { nom: "Jenlain Ambrée", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Jenlain", force: "7,5%", fa: "La bière du Nord qui a relancé la France brassicole en 1974." },
  { nom: "La Choulette Ambrée", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Hargnies", force: "5,9%", fa: "Brassée dans une ancienne ferme-brasserie du Nord : le retour du goût." },
  { nom: "Ch'ti Blonde", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Loos-en-Gohelle", force: "6,4%", fa: "Le Ch'ti à la bière : bienvenue au bistrot du Nord." },
  { nom: "Ch'ti Rousse", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Loos-en-Gohelle", force: "6,4%", fa: "La rousse des mines : le charbon dans le verre, en mieux." },
  { nom: "Mont des Cats", emoji: "⛪", type: "Trappiste", origine: "France — Godewaersvelde", force: "7,6%", fa: "L'unique trappiste française : brassée jadis à l'abbaye, rebaptisée en 2016." },
  { nom: "Bière du Démon", emoji: "😈", type: "Bière forte", origine: "France — Riom", force: "12%", fa: "12% d'alcool : le démon français, à respecter avant de siffler." },
  { nom: "Cervoise Lancelot", emoji: "🌰", type: "Cervoise", origine: "France — Bretagne, Josselin", force: "5,5%", fa: "La cervoise des Gaulois, brassée au foyer d'un château breton." },
  { nom: "Telenn Du", emoji: "🖤", type: "Bière au blé noir", origine: "France — Bretagne, Josselin", force: "4,8%", fa: "Du sarrasin breton : la galette se boit aussi." },
  { nom: "Britt Blonde", emoji: "🇫🇷", type: "Blonde de blé", origine: "France — Bretagne, Trégunc", force: "4,5%", fa: "Le breton la boit à l'apéro : le froment armoricain." },
  { nom: "Britt Rousse", emoji: "🇫🇷", type: "Rousse", origine: "France — Bretagne, Trégunc", force: "5%", fa: "La rousse bretonne : caramel et beurre demi-sel (presque)." },
  { nom: "Meteor Pils", emoji: "🇫🇷", type: "Pilsner", origine: "France — Hochfelden", force: "5%", fa: "L'indépendante d'Alsace : la dernière grande brasserie familiale." },
  { nom: "Meteor Blanc de Blancs", emoji: "🇫🇷", type: "Blanche", origine: "France — Hochfelden", force: "5,5%", fa: "Blanche alsacienne au froment : la couronne des vallées vosgiennes." },
  { nom: "Ninkasi IPA", emoji: "🇫🇷", type: "IPA", origine: "France — Lyon", force: "6%", fa: "Née à Lyon, ville de Ninkasi la déesse sumérienne de la bière." },
  { nom: "Deck & Donohue East Indie Pale Ale", emoji: "🇫🇷", type: "IPA", origine: "France — Montreuil", force: "6%", fa: "Deux Américains à Paris : l'IPA de la capitale redevient honnête." },
  { nom: "La Goutte d'Or", emoji: "🇫🇷", type: "Blonde", origine: "France — Paris 18e", force: "6%", fa: "Brassée dans la Goutte d'Or, comme le vin du même nom jadis." },
  { nom: "Bière du Mont Blanc — La Blonde", emoji: "🏔️", type: "Blonde", origine: "France — Savoie", force: "5%", fa: "Brassée avec l'eau des Alpes : la menthe en moins, la mousse en plus." },
  { nom: "Bière du Mont Blanc — La Rousse", emoji: "🏔️", type: "Rousse", origine: "France — Savoie", force: "6%", fa: "La rousse alpine : de l'eau de fonte des neiges en bouteille." },
  { nom: "Mistral Gagnal", emoji: "⛵", type: "Blonde", origine: "France — Marseille", force: "6%", fa: "Le mistral dans les voiles et dans le comptoir : Marseille brassicole." },
  { nom: "Anosteké Blonde", emoji: "🇫🇷", type: "Bière de garde", origine: "France — Douai", force: "6,5%", fa: "Le refrain des fêtes du Nord : « Anosteké ! » comme disent les Ch'tis." },
  { nom: "Pietra", emoji: "🌰", type: "Bière à la châtaigne", origine: "France — Corse, Furiani", force: "5%", fa: "Brassée avec de la farine de châtaigne corse : la bière du maquis." },
  { nom: "Colomba", emoji: "🕊️", type: "Blanche corse", origine: "France — Corse, Furiani", force: "5%", fa: "La blanche de Pâques en Corse, à la fleur d'oranger." },
  { nom: "Guinness", emoji: "☘️", type: "Stout", origine: "Irlande — Dublin", force: "4,2%", fa: "Bail de 9 000 ans signé par Arthur Guinness. Le père avait laissé 100 £, il les a mis dans la bière." },
  { nom: "Guinness Foreign Extra", emoji: "☘️", type: "Stout", origine: "Irlande — Dublin", force: "7,5%", fa: "La version forte exportée jadis jusqu'aux tropiques : celle qui a conquis l'Afrique de l'Ouest." },
  { nom: "Murphy's", emoji: "🇮🇪", type: "Stout", origine: "Irlande — Cork", force: "4%", fa: "La douce concurrente de la Guinness : moins amère, plus crémeuse." },
  { nom: "Beamish", emoji: "🇮🇪", type: "Stout", origine: "Irlande — Cork", force: "4%", fa: "Le troisième mousquetaire des stouts irlandais, fidèle à Cork." },
  { nom: "Smithwick's", emoji: "🇮🇪", type: "Rousse irlandaise", origine: "Irlande — Kilkenny", force: "4,5%", fa: "La rousse du monastère de Kilkenny, plus vieille brasserie d'Irlande." },
  { nom: "O'Hara's Irish Stout", emoji: "🇮🇪", type: "Stout", origine: "Irlande — Carlow", force: "4,4%", fa: "La stout des artisans de Carlow : le revival irlandais du vrai goût." },
  { nom: "Fuller's London Pride", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Londres", force: "4,7%", fa: "La fierté de Londres depuis 1959 : l'amertume est une politesse." },
  { nom: "Fuller's ESB", emoji: "🇬🇧", type: "Strong bitter", origine: "Angleterre — Londres", force: "5,5%", fa: "La « Extra Special Bitter » par excellence : une championne multicroisée." },
  { nom: "Fuller's London Porter", emoji: "🇬🇧", type: "Porter", origine: "Angleterre — Londres", force: "5,4%", fa: "Le style du port de Londres, ressuscité à Chiswick : noir, doux, profond." },
  { nom: "Fuller's Vintage Ale", emoji: "🇬🇧", type: "Barleywine", origine: "Angleterre — Londres", force: "8,5%", fa: "Millésimée chaque année : on la garde comme un grand vin de Bordeaux." },
  { nom: "Fuller's 1845", emoji: "🇬🇧", type: "Strong ale", origine: "Angleterre — Londres", force: "6,1%", fa: "Brassée pour l'anniversaire de la brasserie : la bouteille à cire rouge." },
  { nom: "Samuel Smith Oatmeal Stout", emoji: "🇬🇧", type: "Stout à l'avoine", origine: "Angleterre — Tadcaster", force: "5%", fa: "L'avoine dans le stout : la texture de velours, brasser depuis 1758." },
  { nom: "Samuel Smith Taddy Porter", emoji: "🇬🇧", type: "Porter", origine: "Angleterre — Tadcaster", force: "5,4%", fa: "Le porter des mineurs du Yorkshire : noir et nourrissant." },
  { nom: "Samuel Smith Old Brewery Pale", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Tadcaster", force: "5%", fa: "Brassée encore en fûts de pierre de Yorkshire : la tradition en bouteille." },
  { nom: "Theakston Old Peculier", emoji: "🇬🇧", type: "Old ale", origine: "Angleterre — Masham", force: "5,6%", fa: "« Peculier » : un mot du droit ecclésiastique, une bière au goût de pruneau." },
  { nom: "Robinson's Old Tom", emoji: "🇬🇧", type: "Barleywine", origine: "Angleterre — Stockport", force: "8,5%", fa: "Élue plusieurs fois « meilleure bière du monde » : le chat sur l'étiquette a bon goût." },
  { nom: "Young's Double Chocolate Stout", emoji: "🍫", type: "Stout chocolaté", origine: "Angleterre — Londres", force: "5%", fa: "Chocolat noir et vanille dans un stout : le dessert des soirs anglais." },
  { nom: "Hook Norton Old Hooky", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Oxfordshire", force: "4,3%", fa: "Brassée avec une machine à vapeur de 1899 : le village se boit à la pompe." },
  { nom: "Timothy Taylor Landlord", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Keighley", force: "4,3%", fa: "La préférée des buveurs anglais : elle a même converti Hollywood." },
  { nom: "St Austell Tribute", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Cornouailles", force: "4,2%", fa: "Brassée pour un eclipse solaire en 1999 : la Cornouailles en fût." },
  { nom: "Wadworth 6X", emoji: "🇬🇧", type: "Strong bitter", origine: "Angleterre — Devizes", force: "6%", fa: "Les livraison se font encore par cheval dans Devizes : la 6X du cocher." },
  { nom: "Shepherd Neame Spitfire", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Faversham", force: "4,5%", fa: "Née pour les 50 ans de la bataille d'Angleterre : l'humour en bouteille." },
  { nom: "Bishop's Finger", emoji: "🇬🇧", type: "Strong ale", origine: "Angleterre — Faversham", force: "5,4%", fa: "Le doigt de l'évêque indique le chemin de la brasserie (vraiment)." },
  { nom: "Harvey's Sussex Best", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Lewes", force: "4%", fa: "Le bitter du Sussex, servi à la parfaite température de cave." },
  { nom: "Adnams Southwold", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Suffolk", force: "4,3%", fa: "La bière des côtes du Suffolk : les mouettes la réclament aussi." },
  { nom: "Hobgoblin", emoji: "🧙", type: "Rousse", origine: "Angleterre — Witney", force: "5,2%", fa: "Le gobelin de Wychwood : la rousse qui a conquis les étudiants anglais." },
  { nom: "Bombardier", emoji: "🇬🇧", type: "English bitter", origine: "Angleterre — Bedford", force: "5,2%", fa: "« English Premium Bitter » : la bière qui se boit comme un hymne." },
  { nom: "Black Sheep Riggwelter", emoji: "🇬🇧", type: "Strong dark ale", origine: "Angleterre — Masham", force: "5,7%", fa: "« Riggwelter » : mot du Yorkshire pour une brebis sur le dos. On comprend après la pinte." },
  { nom: "Innis & Gunn Original", emoji: "🛢️", type: "Bière vieillie en fût", origine: "Écosse — Édimbourg", force: "6,6%", fa: "Vieillie en ex-fûts de whisky : l'Ecosse entière dans une bouteille." },
  { nom: "Traquair House Ale", emoji: "🏰", type: "Strong scotch ale", origine: "Écosse — Innerleithen", force: "7,2%", fa: "Brassée dans la plus ancienne maison habitée d'Ecosse, depuis 1965." },
  { nom: "Fraoch", emoji: "🌸", type: "Heather ale", origine: "Écosse — Glasgow", force: "5%", fa: "Brassée à la bruyère : la recette des Pictes, ressuscitée par les frères Williams." },
  { nom: "BrewDog Punk IPA", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", type: "IPA", origine: "Écosse — Ellon", force: "5,4%", fa: "La punk qui a déridé le Royaume : l'amertume comme manifeste." },
  { nom: "Thornbridge Jaipur", emoji: "🇬🇧", type: "IPA", origine: "Angleterre — Bakewell", force: "5,9%", fa: "L'IPA de la nouvelle vague anglaise : florale, sèche, multiple médaillée." },
  { nom: "Meantime London Pale Ale", emoji: "🇬🇧", type: "Pale ale", origine: "Angleterre — Londres", force: "4,3%", fa: "La pale ale de Greenwich : le méridien de l'amertume britannique." },
  { nom: "Bass Pale Ale", emoji: "🔺", type: "Pale ale", origine: "Angleterre — Burton-upon-Trent", force: "5,2%", fa: "Le triangle rouge : première marque déposée du Royaume-Uni (1876)." },
  { nom: "Harviestoun Bitter & Twisted", emoji: "🇬🇧", type: "Bitter", origine: "Écosse — Alva", force: "4,2%", fa: "Agrumes et amertume sèche : le twist du nom est dans le verre." },
  { nom: "Newcastle Brown Ale", emoji: "🐕", type: "Brown ale", origine: "Angleterre — Newcastle", force: "4,7%", fa: "La « Nukey Brown » des docks : la mousse des travailleurs du Nord." },
  { nom: "Boddingtons", emoji: "🇬🇧", type: "Cream ale", origine: "Angleterre — Manchester", force: "3,5%", fa: "« La crème de Manchester » : le nitro donne une texture de laitue onctueuse." },
  { nom: "Tetley's", emoji: "🇬🇧", type: "Bitter", origine: "Angleterre — Leeds", force: "3,8%", fa: "Le Yorkshire pudding se boit aussi : le bitter de Leeds, très crémeux." },
  { nom: "Sierra Nevada Pale Ale", emoji: "🇺🇸", type: "Pale ale", origine: "États-Unis — Californie", force: "5,6%", fa: "Celle qui a lancé la révolution craft américaine en 1980 : cascade hops forever." },
  { nom: "Sierra Nevada Torpedo", emoji: "🇺🇸", type: "IPA", origine: "États-Unis — Californie", force: "7,2%", fa: "La « Torpedo » : inventée pour injecter le houblon à sec en continu." },
  { nom: "Goose Island IPA", emoji: "🇺🇸", type: "IPA", origine: "États-Unis — Chicago", force: "5,9%", fa: "L'IPA de Chicago, rachetée par AB InBev : les puristes grinceront, elle reste bonne." },
  { nom: "Goose Island Bourbon County", emoji: "🇺🇸", type: "Stout vieilli en bourbon", origine: "États-Unis — Chicago", force: "13%", fa: "Vieillie en fûts de whiskey : chaque Black Friday, les files d'attente s'allongent." },
  { nom: "Sam Adams Boston Lager", emoji: "🇺🇸", type: "Lager", origine: "États-Unis — Boston", force: "4,8%", fa: "Celle qui a prouvé aux Américains que la bière pouvait avoir du goût." },
  { nom: "Sam Adams Utopias", emoji: "🇺🇸", type: "Bière extrême", origine: "États-Unis — Boston", force: "28%", fa: "28% d'alcool, pas de distillation : interdite dans certains États. Le péché mignon des collectionneurs." },
  { nom: "Brooklyn Lager", emoji: "🇺🇸", type: "Lager", origine: "États-Unis — New York", force: "5,2%", fa: "La lager du retour : New York a retrouvé sa bière en 1988." },
  { nom: "Lagunitas IPA", emoji: "🇺🇸", type: "IPA", origine: "États-Unis — Californie", force: "6,2%", fa: "Brassée par des zouaves de Petaluma : l'IA de la désinvolture californienne." },
  { nom: "Lagunitas A Little Sumpin' Sumpin'", emoji: "🇺🇸", type: "Pale ale au froment", origine: "États-Unis — Californie", force: "7,1%", fa: "« Un petit quelque chose » : houblon et froment, le cocktail californien." },
  { nom: "Stone IPA", emoji: "🗿", type: "IPA", origine: "États-Unis — Californie", force: "6,9%", fa: "« Fier. Arrogant. Pas pour tout le monde. » : le gargo en bouteille." },
  { nom: "Ballast Point Sculpin", emoji: "🐟", type: "IPA", origine: "États-Unis — San Diego", force: "7%", fa: "Le poisson-scorpion de San Diego : l'IPA qui a mis la ville sur la carte." },
  { nom: "Russian River Pliny the Elder", emoji: "🌿", type: "Double IPA", origine: "États-Unis — Californie", force: "8%", fa: "Les files d'attente devant la brasserie sont légendaires : la double IPA de référence." },
];
