// ---- Beer Runner — anecdotes EN, partie 5/5 (fin + fusion) ----
const BIERES_CULTES_EN_B = {
  "Meteor Blanc de Blancs": "An Alsatian wheat wit: the crown of the Vosges valleys.",
  "Ninkasi IPA": "Born in Lyon, city of Ninkasi the Sumerian goddess of beer.",
  "Deck & Donohue East Indie Pale Ale": "Two Americans in Paris: the capital's honest IPA.",
  "La Goutte d'Or": "Brewed in the Goutte d'Or district, like the wine once named after it.",
  "Bière du Mont Blanc — La Blonde": "Brewed with Alpine water: less mint, more foam.",
  "Bière du Mont Blanc — La Rousse": "The Alpine red: snowmelt water in a bottle.",
  "Mistral Gagnal": "The mistral in the sails and the counter: Marseille brews.",
  "Anosteké Blonde": "The Northern festivals' refrain: 'Anosteké!' as the Ch'tis say.",
  "Pietra": "Brewed with Corsican chestnut flour: the maquis in a glass.",
  "Colomba": "The Corsican Easter wit, with orange blossom.",
  "Guinness": "Arthur Guinness signed a 9,000-year lease. His father left him 100 pounds — he put them into beer.",
  "Guinness Foreign Extra": "The strong version once exported to the tropics: the one that won West Africa.",
  "Murphy's": "Guinness' gentle Cork rival: less bitter, creamier.",
  "Beamish": "The third musketeer of Irish stouts, loyal to Cork.",
  "Smithwick's": "Kilkenny's monastery red, Ireland's oldest brewery.",
  "O'Hara's Irish Stout": "The Carlow crafters' stout: Ireland's real-taste revival.",
  "Fuller's London Pride": "London's pride since 1959: bitterness as a politeness.",
  "Fuller's ESB": "The 'Extra Special Bitter' par excellence: a many-times champion.",
  "Fuller's London Porter": "The London docklands style, revived at Chiswick: black, soft, deep.",
  "Fuller's Vintage Ale": "Vintage-dated each year: cellared like a fine Bordeaux.",
  "Fuller's 1845": "Brewed for the brewery's anniversary: the red-wax bottle.",
  "Samuel Smith Oatmeal Stout": "Oats in the stout: velvet texture, brewing since 1758.",
  "Samuel Smith Taddy Porter": "The Yorkshire miners' porter: black and nourishing.",
  "Samuel Smith Old Brewery Pale": "Still brewed in Yorkshire stone squares: tradition bottled.",
  "Theakston Old Peculier": "'Peculier' is a church-law word: a prune-flavored old ale.",
  "Robinson's Old Tom": "Several times voted world's best beer: the label cat has good taste.",
  "Young's Double Chocolate Stout": "Dark chocolate and vanilla in a stout: the English dessert.",
  "Hook Norton Old Hooky": "Brewed with an 1899 steam engine: the village pours at the pump.",
  "Timothy Taylor Landlord": "English drinkers' favorite: it even converted Hollywood.",
  "St Austell Tribute": "Brewed for the 1999 solar eclipse: Cornwall in a cask.",
  "Wadworth 6X": "Deliveries are still made by horse-drawn dray in Devizes: the drayman's 6X.",
  "Shepherd Neame Spitfire": "Born for the Battle of Britain's 50th anniversary: humor in a bottle.",
  "Bishop's Finger": "The bishop's finger really does point the way to the brewery.",
  "Harvey's Sussex Best": "The Sussex bitter, served at the perfect cellar temperature.",
  "Adnams Southwold": "The Suffolk coast beer: the seagulls demand some too.",
  "Hobgoblin": "Wychwood's goblin: the red that conquered English students.",
  "Bombardier": "'English Premium Bitter': the beer you drink like an anthem.",
  "Black Sheep Riggwelter": "'Riggwelter' is Yorkshire for a sheep on its back. You get it after the pint.",
  "Innis & Gunn Original": "Aged in ex-whisky casks: all of Scotland in one bottle.",
  "Traquair House Ale": "Brewed in Scotland's oldest inhabited house, since 1965.",
  "Fraoch": "Brewed with heather: the Picts' recipe, revived by the Williams brothers.",
  "BrewDog Punk IPA": "The punk that unbuttoned Britain: bitterness as a manifesto.",
  "Thornbridge Jaipur": "The new-wave English IPA: floral, dry, many times medaled.",
  "Meantime London Pale Ale": "Greenwich's pale ale: the meridian of British bitterness.",
  "Bass Pale Ale": "The red triangle: the UK's first registered trademark (1876).",
  "Harviestoun Bitter & Twisted": "Citrus and dry bitterness: the name's twist is in the glass.",
  "Newcastle Brown Ale": "The docks' 'Nukey Brown': Northern workers' foam.",
  "Boddingtons": "'The cream of Manchester': nitro gives a lush texture.",
  "Tetley's": "The Yorkshire pudding drinks too: Leeds' very creamy bitter.",
  "Sierra Nevada Pale Ale": "The one that launched America's craft revolution in 1980.",
  "Sierra Nevada Torpedo": "The 'Torpedo': invented to dry-hop in a continuous stream.",
  "Goose Island IPA": "Chicago's IPA, bought by AB InBev: purists wince, it stays good.",
  "Goose Island Bourbon County": "Whiskey-barrel aged: every Black Friday the queues grow.",
  "Sam Adams Boston Lager": "The one that proved Americans beer could have taste.",
  "Sam Adams Utopias": "28% alcohol, undistilled: banned in some states. Collectors' darling.",
  "Brooklyn Lager": "The comeback lager: New York got its beer back in 1988.",
  "Lagunitas IPA": "Brewed by Petaluma's rascals: insolence with a hop kick.",
  "Lagunitas A Little Sumpin' Sumpin'": "'A little something': hops and wheat, the Californian cocktail.",
  "Stone IPA": "'Proud. Arrogant. Not for everyone.': the gargoyle in a bottle.",
  "Ballast Point Sculpin": "San Diego's sculpin fish: the IPA that put the city on the map.",
  "Russian River Pliny the Elder": "The brewery queues are legendary: the reference double IPA.",
  "Dogfish Head 60 Minute": "Hopped continuously for 60 minutes: the scholars' IPA.",
  "Dogfish Head 120 Minute": "18% and still standing: the monster to sip like port.",
  "Bell's Two Hearted": "Hemingway's trout river: contest judges' perfect IPA.",
  "New Belgium Fat Tire": "Named after the founder's bike ride in France: America's nicest amber.",
  "Anchor Steam": "Steam-fermented on San Francisco rooftops since 1896.",
  "The Alchemist Heady Topper": "Sold only at the brewery, in cans: the hop pilgrims' grail.",
  "Boulevard Tank 7": "America's saison: born from a cask 'gone wrong' that became a cult.",
  "Victory Prima Pils": "America's honest pils: dry, floral, true to old Europe.",
  "New Glarus Spotted Cow": "Unfindable outside Wisconsin: the Midwest's best-kept secret.",
  "Left Hand Milk Stout": "Lactose softens the black: milk texture, night color.",
  "Oskar Blues Dale's Pale Ale": "The first craft in a can (2002): 'canned beer is good', they said.",
  "Pabst Blue Ribbon": "Blue ribbon won in 1893, dusted off by hipsters.",
  "Blue Moon": "The Rockies' wit, with its mandatory orange wheel.",
  "Deschutes Fresh Squeezed": "Squeezed the day, as its name says: Oregon in citrus.",
  "Pilsner Urquell": "The very first pilsner (1842). Every lager on Earth descends from it.",
  "Budweiser Budvar": "The 'real' Czech Budweiser: the lawsuit with the American one runs since 1907.",
  "Budvar Dark": "Budvar's black one: malt caramel, softness, great craft.",
  "Kozel": "The billy goat on the label, guardian of the brewing village.",
  "Kozel Černý": "The goat's black one: light, coffee, drank by the Czech pint.",
  "Staropramen": "Prague's pub beer: the Smíchov 'great toast'.",
  "Bernard": "Brewed with Bohemian-Moravian spring water: unfiltered in the 'Family' version.",
  "Krušovice": "The Bohemian kings' beer, served at court since the 16th century.",
  "U Fleků": "Brewed on the spot in Prague since 1499: the city's oldest taproom.",
  "Primátor": "The Náchod fortress beer: guardians of taste.",
  "Heineken": "The 'star' foam: the brewer's A-yeast invention deserves a glass.",
  "La Trappe Quadrupel": "The mother quadrupel: born at Koningshoeven, strong as the monks' faith.",
  "La Trappe Dubbel": "The Dutch monks' dubbel: the country's only Trappist monastery.",
  "La Trappe Bockbier": "The monks' bock: brewed once a year, autumn in a bottle.",
  "Zundert": "Van Gogh's village Trappist: golden, spiced, rare.",
  "Grolsch": "The swing-top 'beugel' cap: the sound of the Dutch weekend.",
  "Hertog Jan Dubbel": "'Duke John' brews in Arcen: Limburg has taste.",
  "De Molen Hel & Verdoemenis": "'Hell and damnation': an imperial stout built for the cellar.",
  "'t IJ Zatte": "Brewed under an Amsterdam windmill: the Zeeburg 'drunk one'.",
  "Texels Skuumkoppe": "Brewed on the island of sheep: the sea is in the foam.",
  "Samichlaus": "Brewed once a year on December 6: 'Santa Claus' in Swiss-German. The strongest of lagers.",
  "Stift Engelszell Gregorius": "The Danube valley's Trappist: Austria's first.",
  "Stift Engelszell Benno": "Engelszell's second Trappist: smoke and wheat at the monastery.",
  "Ottakringer": "Vienna's wine-tavern beer: summer in Ottakring is also a festival.",
  "Stiegl": "Salzburg's brewery since 1492: Mozart drank stronger than his operas.",
  "Feldschlösschen": "Brewed in a castle shaped like... a castle: the scenery drinks with you.",
  "Appenzeller Vollmond": "Brewed only on full-moon nights: the astronomical beer.",
  "Carlsberg": "The Carlsberg lab isolated pure yeast in 1883: science in the bottle.",
  "Tuborg": "The Danish 'J-day' beer: the day the country drinks its first Christmas Tuborg.",
  "Mikkeller Beer Geek Breakfast": "The geeks' breakfast: oats and coffee in a stout.",
  "Nøgne Ø India Pale Ale": "'Naked island': Norway's southern brewery, fjord bitterness.",
  "Lammin Sahti": "The Finnish sahti: filtered through juniper branches, EU-protected.",
  "Fix": "Athens' beer of 1864: the smell of Piraeus in a bottle.",
  "Mythos": "Greek mythology drinks ice cold, facing the Aegean Sea.",
  "Tipopils": "Milan's cult pils: 'Tipopils' is a local religion.",
  "Baladin Nora": "A recipe inspired by pharaonic beers: saffron and myrtle in the glass.",
  "Baladin Xyauyu": "Cask-aged like balsamic vinegar: Modena's barley wine.",
  "Del Borgo Re Ale": "The Italian new wave: Timut pepper and creamy foam.",
  "Ichnusa": "Sardinia's beer, named after the Ichnusa fairy legend.",
  "Moretti": "The label's mustached gentleman really existed: a gentleman met in 1942.",
  "Menabrea": "Italy's oldest beer (1846): a very dignified Piedmont blond.",
  "Estrella Damm": "Barcelona's star since 1876: paella pairs well with it.",
  "Estrella Galicia": "Galicia's beer: the pilgrimage route has its own star.",
  "Mahou Cinco Estrellas": "Madrid's five stars: after the Real, the city's second pride.",
  "Alhambra Reserva 1925": "The unique green bottle: Granada's beer, sipped facing the Sierra.",
  "La Virgen": "Madrid's craft blond, brewed in sight of the Paseo: the chapel of taste.",
  "Super Bock": "The North's super: francesinha eaters demand it.",
  "Sagres": "The 1940 exhibition's beer: Portuguese sun in a can.",
  "Żywiec": "The Tatra mountains' beer since 1856: Polish highlands in a pint.",
  "Tyskie": "The Polish kings' beer, say the drinkers of Tychy.",
  "Okocim": "The brewery of John III Sobieski... almost: Okocim has brewed since 1845.",
  "Warka": "Casimir the Great's beer, say the experts: Warka is the doyenne.",
  "Żywiec Porter": "The Polish Baltic porter: 9.5% of hoppy tradition.",
  "Okocim Porter": "The Vistula banks' Baltic porter: the Polish cold drinks black.",
  "Grodziskie": "The 'Polish champagne': smoked wheat, fine bubbles, a revived style.",
  "Asahi Super Dry": "The 'karakuchi': dryness conquered the archipelago in 1987.",
  "Sapporo": "The snow city's beer: Sapporo's star has shone since 1876.",
  "Kirin Ichiban": "'Ichiban Shibori': only the wort's first pressing, a luxury.",
  "Yebisu": "Sapporo's big sister: the premium convenience-store beer.",
  "Hitachino Nest White Ale": "Brewed in a sake brewery: the yeasts speak different languages.",
  "Hitachino Red Rice": "Brewed with fermented red rice: sake crashes the beer party.",
  "Tsingtao": "Legacy of the 1903 German colony: China's most exported beer.",
  "Singha": "Thailand's lion: heat is drunk cold, the lion never sleeps.",
  "Bia Hanoi": "Hanoi's draft beer, sipped on red stools by the roadside.",
  "Tiger": "Singapore's tiger (1932): the beer that crossed the Malacca Strait.",
  "Corona": "Lime masks the taste of sunshine: the beach sold in a clear bottle.",
  "Pacifico": "Mazatlán's surfers' beer: the wave you can drink.",
  "Dos Equis XX": "'The Most Interesting Man in the World': the funniest ad ever.",
  "Modelo Negra": "Mexico City's black one: the beer version of mole, spice and caramel.",
  "Bohemia": "The Mexican beers' 'Silver Conch': the brewery's old lady.",
  "Quilmes": "Argentina's football beer: the game is watched with family and Quilmes.",
  "Cusqueña": "Machu Picchu's beer at 3,400 m: the highest brewery beer in the world.",
  "Polar": "The Andes' polar bear: Venezuelan freshness goes with arepas.",
  "Unibroue La Fin du Monde": "'The end of the world': explorers sought India, they found Québec.",
  "Unibroue Blanche de Chambly": "The Chambly fort's wit: New France drinks white.",
  "Unibroue Maudite": "The 'damned one': the flying canoe legend of the voyageurs.",
  "Unibroue Trois Pistoles": "The Québec village's black horse: the legend drinks black.",
  "Molson Canadian": "North America's oldest brewery (1786): the river drinks too.",
  "Coopers Sparkling Ale": "Bottle-conditioned: the yeast sediment is an honor, not a flaw.",
  "Little Creatures Pale Ale": "Born in a former crocodile-filet factory: the crocodile of pale ales.",
  "James Squire 150 Lashes": "Australia's first brewer was a deported thief: he got '150 lashes'.",
  "Coopers Pale Ale": "The barbie's red tin: bottle-conditioned, cloudy, legendary.",
  "Baltika 9": "The 'devyatka': St Petersburg's strong one, respect it in winter.",
  "Efes": "The Bosphorus beer: meze is drunk cold.",
  "Ursus": "The Transylvanian bear: the beer watches over the Carpathians.",
  "Zlatorog": "The Julian Alps' golden ibex: the legend drinks cold.",
  "Zlatý Bažant": "Slovakia's golden pheasant: the south of the country has treasures.",
  "Dreher": "Antal Dreher invented Vienna lager in Budapest: the family still reigns.",
  "Obolon": "The Dnieper's beer: the river gives the water, Kyiv gives the foam.",
  "Castle Lager": "The braai's beer (South African barbecue): the castle of taste.",
  "Tusker": "Kenya's elephant: the savanna drinks very cold.",
  "Erdinger Dunkel": "The wheat dark: Bavarian toasted bread.",
  "Founders KBS": "Breakfast Stout aged in bourbon barrels: 'Kentucky Breakfast', champions' morning.",
  "Founders Breakfast Stout": "Coffee and double-cream chocolate stout: Michigan's official breakfast.",
  "Great Lakes Edmund Fitzgerald": "Named after the freighter that sank in Lake Erie: the sailors' porter.",
  "Löwenbräu": "The Munich lion again, bare: at Oktoberfest the lion roars in liters.",
  "Hacker-Pschorr": "The 'people's friend': the Munich revolutions' brewery.",
  "Spaten": "The brewery's 'spade': the first to advertise, back in 1894.",
  "Harvey's Tom Paine": "Named after Lewes' revolutionary: the beer of human rights.",
  "Hoegaarden Grand Cru": "The wit boosted with coriander and curaçao: wheat's grand reserve.",
  "St Bernardus Tripel": "Watou phoenix's tripel: round, spiced, silk foam.",
  "Weihenstephaner Pils": "The Bavarian monks' pils: Cistercian order meets Hallertau hops.",
  "Orval Grande Réserve": "Orval laid down: numbered bottles vanish in a blink.",
  "Cantillon Vigneronne": "Muscat grapes on lambic: the brewery bows to wine, quietly.",
  "Grimbergen Rouge": "The phoenix turns red: red fruit and caramel notes.",
  "Samuel Smith Nut Brown Ale": "Yorkshire's nutty brown: as soft as a pub by the fire.",
};
// dictionnaire complet des anecdotes anglaises
const BIERES_CULTES_EN = { ...BIERES_CULTES_EN_A, ...BIERES_CULTES_EN_B };
