// ---- Beer Runner — bières cultes, partie 3/5 (fin du catalogue + concaténation) ----
const BIERES_CULTES_C = [
  { nom: "Dogfish Head 60 Minute", emoji: "🦺", type: "IPA", origine: "États-Unis — Delaware", force: "6%", fa: "Houblonnée 60 minutes en continu : l'IPA des érudits." },
  { nom: "Dogfish Head 120 Minute", emoji: "⏱️", type: "IPA extrême", origine: "États-Unis — Delaware", force: "18%", fa: "18% et toujours debout : le monstre à siroter comme un porto." },
  { nom: "Bell's Two Hearted", emoji: "🎣", type: "IPA", origine: "États-Unis — Michigan", force: "7%", fa: "La rivière à truites de Hemingway : l'IPA parfaite d'après les concours." },
  { nom: "New Belgium Fat Tire", emoji: "🚂", type: "Amber ale", origine: "États-Unis — Colorado", force: "5,2%", fa: "Nommée d'après le vélo du fondateur en France : l'amber la plus sympa des States." },
  { nom: "Anchor Steam", emoji: "🌉", type: "Steam beer", origine: "États-Unis — San Francisco", force: "4,9%", fa: "Fermentée à la vapeur sur les toits de San Francisco depuis 1896." },
  { nom: "The Alchemist Heady Topper", emoji: "⚡", type: "Double IPA", origine: "États-Unis — Vermont", force: "8%", fa: "Vendue uniquement à la brasserie, en canette : le graal des pèlerins houblonnés." },
  { nom: "Boulevard Tank 7", emoji: "🌻", type: "Saison américaine", origine: "États-Unis — Kansas City", force: "8,5%", fa: "La saison des Américains : née d'un fût « raté » devenu culte." },
  { nom: "Victory Prima Pils", emoji: "🇺🇸", type: "Pilsner", origine: "États-Unis — Pennsylvanie", force: "5,3%", fa: "La pils américaine du vrai : sèche, florale, fidèle à la vieille Europe." },
  { nom: "New Glarus Spotted Cow", emoji: "🐄", type: "Cream ale", origine: "États-Unis — Wisconsin", force: "4,8%", fa: "Introuvable hors du Wisconsin : le secret le mieux gardé du Middle West." },
  { nom: "Left Hand Milk Stout", emoji: "🥛", type: "Stout au lactose", origine: "États-Unis — Colorado", force: "6%", fa: "Le lactose adoucit le noir : la texture de lait, la couleur de nuit." },
  { nom: "Oskar Blues Dale's Pale Ale", emoji: "🎸", type: "Pale ale en canette", origine: "États-Unis — Colorado", force: "6,5%", fa: "La première craft en canette (2002) : « canned beer is good » disaient-ils." },
  { nom: "Pabst Blue Ribbon", emoji: "🏆", type: "Lager", origine: "États-Unis — Milwaukee", force: "4,7%", fa: "Ribbon bleu gagné en 1893, ressortie du placard par les hipsters." },
  { nom: "Blue Moon", emoji: "🌙", type: "Blanche", origine: "États-Unis — Colorado", force: "5,4%", fa: "La blanche des Rocheuses, avec sa rondelle d'orange obligatoire." },
  { nom: "Deschutes Fresh Squeezed", emoji: "🍊", type: "IPA", origine: "États-Unis — Oregon", force: "6,4%", fa: "Pressée du jour, comme son nom l'indique : l'Oregon en agrumes." },
  { nom: "Pilsner Urquell", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Plzeň", force: "4,4%", fa: "La toute première pilsner (1842). Toutes les blondes du monde descendent d'elle." },
  { nom: "Budweiser Budvar", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — České Budějovice", force: "5%", fa: "La « vraie » Budweiser tchèque : le procès avec l'Américaine dure depuis 1907." },
  { nom: "Budvar Dark", emoji: "🇨🇿", type: "Dunkel tchèque", origine: "Tchéquie — České Budějovice", force: "4,7%", fa: "La noire de Budvar : du caramel de malt, de la douceur, du grand art." },
  { nom: "Kozel", emoji: "🐐", type: "Pilsner", origine: "Tchéquie — Velké Popovice", force: "4,6%", fa: "Le bouc sur l'étiquette, gardien du village brassicole." },
  { nom: "Kozel Černý", emoji: "🐐", type: "Dunkel", origine: "Tchéquie — Velké Popovice", force: "3,8%", fa: "La noire du bouc : légère, café, à boire en pinte tchèque." },
  { nom: "Staropramen", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Prague", force: "5%", fa: "La bière des bars de Prague : le « grand toast » du Smíchov." },
  { nom: "Bernard", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Humpolec", force: "5%", fa: "Brassée avec de l'eau de source de Bohême-Moravie : non filtrée en version «Family»." },
  { nom: "Krušovice", emoji: "🇨🇿", type: "Lager", origine: "Tchéquie — Krušovice", force: "5%", fa: "La bière des rois de Bohême, servie à la cour depuis le XVIe." },
  { nom: "U Fleků", emoji: "🕰️", type: "Dunkel de brasserie", origine: "Tchéquie — Prague", force: "5%", fa: "Brassée sur place à Prague depuis 1499 : le plus vieux comptoir de la ville." },
  { nom: "Primátor", emoji: "🇨🇿", type: "Pilsner", origine: "Tchéquie — Náchod", force: "5%", fa: "La bière de la forteresse de Náchod : la garde du goût." },
  { nom: "Heineken", emoji: "🇳🇱", type: "Lager", origine: "Pays-Bas — Amsterdam", force: "5%", fa: "La mousse « vedette » : le brasseur a inventé la levure A, il faut bien la boire." },
  { nom: "La Trappe Quadrupel", emoji: "⛪", type: "Trappiste quadrupel", origine: "Pays-Bas — Berkel-Enschot", force: "10%", fa: "La quadrupel mère : née à Koningshoeven, forte comme la foi des moines." },
  { nom: "La Trappe Dubbel", emoji: "⛪", type: "Trappiste dubbel", origine: "Pays-Bas — Berkel-Enschot", force: "7%", fa: "La dubbel des moines néerlandais : le seul monastère trappiste du pays." },
  { nom: "La Trappe Bockbier", emoji: "⛪", type: "Trappiste bock", origine: "Pays-Bas — Berkel-Enschot", force: "7%", fa: "La bock des moines : brassée une fois l'an, l'automne en bouteille." },
  { nom: "Zundert", emoji: "⛪", type: "Trappiste triple", origine: "Pays-Bas — Zundert", force: "8,2%", fa: "La trappiste du village de Van Gogh : dorée, épicée, rare." },
  { nom: "Grolsch", emoji: "🇳🇱", type: "Lager", origine: "Pays-Bas — Enschede", force: "5%", fa: "Le bouchon à levier « beugle » : le son du weekend néerlandais." },
  { nom: "Hertog Jan Dubbel", emoji: "🇳🇱", type: "Dubbel", origine: "Pays-Bas — Arcen", force: "7%", fa: "Le « duc Jean » brasse à Arcen : le Limbourg a du goût." },
  { nom: "De Molen Hel & Verdoemenis", emoji: "😈", type: "Stout impérial", origine: "Pays-Bas — Bodegraven", force: "11%", fa: "« Enfer et damnation » : un stout impérial taillé pour la cave." },
  { nom: "'t IJ Zatte", emoji: "🌬️", type: "Belgian-style strong ale", origine: "Pays-Bas — Amsterdam", force: "7,5%", fa: "Brassée sous un moulin à vent d'Amsterdam : la « saoule » du Zeeburg." },
  { nom: "Texels Skuumkoppe", emoji: "🐑", type: "Blonde", origine: "Pays-Bas — île de Texel", force: "5%", fa: "Brassée sur l'île des moutons : la mer est dans la mousse." },
  { nom: "Samichlaus", emoji: "🎅", type: "Doppelbock de Noël", origine: "Autriche — Vöslau", force: "14%", fa: "Brewed once a year le 6 décembre : « Père Noël » en suisse-allemand. La plus forte des lagers." },
  { nom: "Stift Engelszell Gregorius", emoji: "⛪", type: "Trappiste", origine: "Autriche — Engelhartszell", force: "9,7%", fa: "La trappiste de la vallée du Danube : la première d'Autriche." },
  { nom: "Stift Engelszell Benno", emoji: "⛪", type: "Trappiste", origine: "Autriche — Engelhartszell", force: "8%", fa: "La seconde trappiste d'Engelszell : fumée et froment au monastère." },
  { nom: "Ottakringer", emoji: "🇦🇹", type: "Lager", origine: "Autriche — Vienne", force: "5,5%", fa: "La bière des guinguettes viennoises : l'été à Ottakring s'appelle aussi festival." },
  { nom: "Stiegl", emoji: "🇦🇹", type: "Lager", origine: "Autriche — Salzbourg", force: "4,9%", fa: "La brasserie de Salzbourg depuis 1492 : Mozart buvait plus fort que ses opéras." },
  { nom: "Feldschlösschen", emoji: "🇨🇭", type: "Lager", origine: "Suisse — Rheinfelden", force: "5%", fa: "Brassée dans un château en forme de… château : le décor boit avec toi." },
  { nom: "Appenzeller Vollmond", emoji: "🌕", type: "Bières de pleine lune", origine: "Suisse — Appenzell", force: "5,2%", fa: "Brassée uniquement les nuits de pleine lune : la bière astronomique." },
  { nom: "Carlsberg", emoji: "🇩🇰", type: "Pilsner", origine: "Danemark — Copenhague", force: "3,8%", fa: "Le laboratoire Carlsberg a isolé la levure pure en 1883 : la science dans la bouteille." },
  { nom: "Tuborg", emoji: "🇩🇰", type: "Pilsner", origine: "Danemark — Copenhague", force: "4,6%", fa: "La bière du « J-day » danois : le jour où le pays boit sa première Tuborg de Noël." },
  { nom: "Mikkeller Beer Geek Breakfast", emoji: "🥣", type: "Stout au café", origine: "Danemark — Copenhague", force: "7,5%", fa: "Le petit-déjeuner des geeks : avoine et café en stout." },
  { nom: "Nøgne Ø India Pale Ale", emoji: "🇳🇴", type: "IPA", origine: "Norvège — Grimstad", force: "9%", fa: "« Île nue » : la brasserie du sud norvégien, l'amertume des fjords." },
  { nom: "Lammin Sahti", emoji: "🐟", type: "Sahti", origine: "Finlande — Lammi", force: "8%", fa: "Le sahti finlandais : filtré à travers des branches de genévrier, protégé par l'UE." },
  { nom: "Fix", emoji: "🇬🇷", type: "Lager", origine: "Grèce — Athènes", force: "4,7%", fa: "La bière duAthènes de 1864 : l'odeur du Pirée en bouteille." },
  { nom: "Mythos", emoji: "🇬🇷", type: "Lager", origine: "Grèce — Athènes", force: "4,7%", fa: "La mythologie se boit très fraîche, face à la mer Égée." },
  { nom: "Tipopils", emoji: "🇮🇹", type: "Pilsner artisanale", origine: "Italie — Lombardie", force: "5,2%", fa: "La pils de culte de Milan : le « Tipopils » est une religion locale." },
  { nom: "Baladin Nora", emoji: "🏺", type: "Bière aux épices égyptiennes", origine: "Italie — Piola", force: "6,8%", fa: "Recette inspirée des bières pharaoniques : safran et myrte dans le verre." },
  { nom: "Baladin Xyauyu", emoji: "🇮🇹", type: "Barleywine vieillie", origine: "Italie — Piola", force: "14%", fa: "Vieillie en fûts comme un vinaigre balsamique : l'orge de Modène." },
  { nom: "Del Borgo Re Ale", emoji: "🌶️", type: "Amber ale épicée", origine: "Italie — Borgorose", force: "6,5%", fa: "La nouvelle vague italienne : poivre de Timut et mousse crémeuse." },
  { nom: "Ichnusa", emoji: "🇮🇹", type: "Lager", origine: "Italie — Sardaigne", force: "4,7%", fa: "La bière de Sardaigne, au nom de la légende de la fée Ichnusa." },
  { nom: "Moretti", emoji: "🇮🇹", type: "Lager", origine: "Italie — Udine", force: "4,6%", fa: "Le moustachu de l'étiquette existe vraiment : un gentleman croisé en 1942." },
  { nom: "Menabrea", emoji: "🇮🇹", type: "Lager", origine: "Italie — Biella", force: "4,8%", fa: "La plus ancienne bière italienne (1846) : une blonde du Piémont très dignifiée." },
  { nom: "Estrella Damm", emoji: "🇪🇸", type: "Lager", origine: "Espagne — Barcelone", force: "4,6%", fa: "L'étoile de Barcelone depuis 1876 : la paella se boit aussi." },
  { nom: "Estrella Galicia", emoji: "🇪🇸", type: "Lager", origine: "Espagne — La Corogne", force: "5,5%", fa: "La bière de Galice : la route du pèlerinage a son étoile." },
  { nom: "Mahou Cinco Estrellas", emoji: "🇪🇸", type: "Lager", origine: "Espagne — Madrid", force: "5,1%", fa: "Les cinq étoiles de Madrid : après le Real, c'est la deuxième fierté locale." },
  { nom: "Alhambra Reserva 1925", emoji: "🕌", type: "Lager verte", origine: "Espagne — Grenade", force: "6,4%", fa: "La bouteille verte unique : la bière de l'Alhambra, à boire face à la Sierra." },
  { nom: "La Virgen", emoji: "🇪🇸", type: "Blonde artisanale", origine: "Espagne — Madrid", force: "4,7%", fa: "La « Vierge » de Madrid, brassée à la vue du Paseo : la chapelle du goût." },
  { nom: "Super Bock", emoji: "🇵🇹", type: "Lager", origine: "Portugal — Porto", force: "5,2%", fa: "La super du Nord : les amateurs de francesinha la réclament." },
  { nom: "Sagres", emoji: "🇵🇹", type: "Lager", origine: "Portugal — Almada", force: "4,9%", fa: "La bière de l'exposition de 1940 : le soleil du Portugal en canette." },
  { nom: "Żywiec", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Żywiec", force: "5,6%", fa: "La bière des Tatras depuis 1856 : la montagne polonaise dans la pinte." },
  { nom: "Tyskie", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Tychy", force: "5,2%", fa: "La bière des rois de Pologne, disent les buveurs de Tychy." },
  { nom: "Okocim", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Brzesko", force: "5%", fa: "La brasserie de John II Sobieski… presque : Okocim brasse depuis 1845." },
  { nom: "Warka", emoji: "🇵🇱", type: "Lager", origine: "Pologne — Warka", force: "5,2%", fa: "La bière de Casimir le Grand disent les cracs : Warka est la doyenne." },
  { nom: "Żywiec Porter", emoji: "⚫", type: "Porter balte", origine: "Pologne — Żywiec", force: "9,5%", fa: "Le porter balte polonais : 9,5% de traditions houblonnées." },
  { nom: "Okocim Porter", emoji: "⚫", type: "Porter balte", origine: "Pologne — Brzesko", force: "8,3%", fa: "Le porter des bords de la Vistule : le froid polonais se boit noir." },
  { nom: "Grodziskie", emoji: "🌾", type: "Bière de froment fumé", origine: "Pologne — Grodzisk", force: "3%", fa: "Le « champagne polonais » : froment fumé, bulles fines, style ressuscité." },
  { nom: "Asahi Super Dry", emoji: "🇯🇵", type: "Dry lager", origine: "Japon — Tokyo", force: "5%", fa: "Le « karakuchi » : la dryness a conquis l'archipel en 1987." },
  { nom: "Sapporo", emoji: "🇯🇵", type: "Lager", origine: "Japon — Sapporo", force: "5%", fa: "La bière de la neige : l'étoile de Sapporo brille depuis 1876." },
  { nom: "Kirin Ichiban", emoji: "🇯🇵", type: "Lager", origine: "Japon — Tokyo", force: "5%", fa: "« Ichiban Shibori » : uniquement le premier pressage du moût, un luxe." },
  { nom: "Yebisu", emoji: "🇯🇵", type: "Lager premium", origine: "Japon — Tokyo", force: "5,5%", fa: "La grande soeur de la Sapporo : le conbini de haut standing." },
  { nom: "Hitachino Nest White Ale", emoji: "🍺", type: "Weizen japonaise", origine: "Japon — Ibaraki", force: "5,5%", fa: "Brassée dans une brasserie de sake : les levures ne parlent pas la même langue." },
  { nom: "Hitachino Red Rice", emoji: "🏮", type: "Rice ale", origine: "Japon — Ibaraki", force: "7%", fa: "Brassée avec du riz rouge fermenté : le sake s'invite dans la bière." },
  { nom: "Tsingtao", emoji: "🇨🇳", type: "Lager", origine: "Chine — Qingdao", force: "4,8%", fa: "Héritage de la colonie allemande de 1903 : la bière de Chine la plus exportée." },
  { nom: "Singha", emoji: "🇹🇭", type: "Lager", origine: "Thaïlande — Bangkok", force: "5%", fa: "Le lion de Thaïlande : la chaleur se boit fraîche, le lion ne dort jamais." },
  { nom: "Bia Hanoi", emoji: "🇻🇳", type: "Lager", origine: "Vietnam — Hanoï", force: "4,2%", fa: "La bière pression de Hanoï, bue sur des tabourets rouges au bord de la rue." },
  { nom: "Tiger", emoji: "🇸🇬", type: "Lager", origine: "Singapour", force: "5%", fa: "Le tigre de Singapour (1932) : la bière qui a traversé le détroit de Malacca." },
  { nom: "Corona", emoji: "🇲🇽", type: "Lager claire", origine: "Mexique — Ciudad de México", force: "4,5%", fa: "Le citron vert masque le goût du soleil : la plage vendue en bouteille transparente." },
  { nom: "Pacifico", emoji: "🌊", type: "Lager", origine: "Mexique — Mazatlán", force: "4,5%", fa: "La bière des surfeurs de Mazatlán : la vague se boit." },
  { nom: "Dos Equis XX", emoji: "🇲🇽", type: "Lager ambrée", origine: "Mexique — Monterrey", force: "4,8%", fa: "« The Most Interesting Man in the World » : la pub la plus drôle du monde." },
  { nom: "Modelo Negra", emoji: "🇲🇽", type: "Dunkel", origine: "Mexique — Mexico", force: "5,3%", fa: "La noire de Mexico : le mole de la bière, épices et caramel." },
  { nom: "Bohemia", emoji: "🇲🇽", type: "Pilsner", origine: "Mexique — Mexico", force: "5%", fa: "La « Concha de Plata » des bières mexicaines : la vieille dame de la brasserie." },
  { nom: "Quilmes", emoji: "🇦🇷", type: "Lager", origine: "Argentine — Quilmes", force: "4,8%", fa: "La bière du football argentin : le foot se boit en famille." },
  { nom: "Cusqueña", emoji: "🇵🇪", type: "Lager", origine: "Pérou — Cusco", force: "5%", fa: "La bière du Machu Picchu, à 3400 mètres d'altitude : la bière la plus haute du monde." },
  { nom: "Polar", emoji: "🇻🇪", type: "Lager", origine: "Venezuela — Caracas", force: "4,5%", fa: "L'ours polaire des Andes vénézuéliennes : la fraîcheur se boit en arepas." },
  { nom: "Unibroue La Fin du Monde", emoji: "🍁", type: "Triple", origine: "Canada — Chambly", force: "9%", fa: "« La fin du monde » : les explorateurs cherchaient l'Inde, ils ont trouvé le Québec." },
  { nom: "Unibroue Blanche de Chambly", emoji: "🍁", type: "Blanche", origine: "Canada — Chambly", force: "5%", fa: "La blanche du fort de Chambly : la Nouvelle-France se boit blanche." },
  { nom: "Unibroue Maudite", emoji: "🍁", type: "Strong amber", origine: "Canada — Chambly", force: "8%", fa: "La « damnée » : la légende du canot volant des voyageurs." },
  { nom: "Unibroue Trois Pistoles", emoji: "🍁", type: "Strong dark", origine: "Canada — Trois-Pistoles", force: "9%", fa: "Le cheval noir du village québécois : la légende se boit noire." },
  { nom: "Molson Canadian", emoji: "🍁", type: "Lager", origine: "Canada — Montréal", force: "5%", fa: "La plus vieille brasserie d'Amérique du Nord (1786) : le fleuve se boit." },
  { nom: "Coopers Sparkling Ale", emoji: "🇦🇺", type: "Ale", origine: "Australie — Adélaïde", force: "5,8%", fa: "Refermentée en bouteille : le dépôt de levure est un honneur, pas un défaut." },
  { nom: "Little Creatures Pale Ale", emoji: "🐬", type: "Pale ale", origine: "Australie — Fremantle", force: "5,4%", fa: "Née dans une ancienne usine de filets de crocodile : la crocodile de la pale ale." },
  { nom: "James Squire 150 Lashes", emoji: "🇦🇺", type: "Pale ale", origine: "Australie — Sydney", force: "4,2%", fa: "Le premier brasseur australien était un voleur déporté : il a eu « 150 coups de fouet »." },
  { nom: "Coopers Pale Ale", emoji: "🇦🇺", type: "Ale", origine: "Australie — Adélaïde", force: "4,5%", fa: "La boîte rouge de la barbie : refermentée, voilée, légendaire." },
  { nom: "Baltika 9", emoji: "🇷🇺", type: "Strong lager", origine: "Russie — Saint-Pétersbourg", force: "8%", fa: "La « devyatka » : la forte de Saint-Pétersbourg, à respecter l'hiver." },
  { nom: "Efes", emoji: "🇹🇷", type: "Lager", origine: "Turquie — Istanbul", force: "5%", fa: "La bière de Bosphore : le mezze se boit fraîche." },
  { nom: "Ursus", emoji: "🇷🇴", type: "Lager", origine: "Roumanie — Cluj", force: "5%", fa: "L'ours de Transylvanie : la bière veille sur les Carpates." },
  { nom: "Zlatorog", emoji: "🇸🇮", type: "Lager", origine: "Slovénie — Laško", force: "5%", fa: "Le bouquetin d'or des Alpes juliennes : la légende se boit fraîche." },
  { nom: "Zlatý Bažant", emoji: "🇸🇰", type: "Lager", origine: "Slovaquie — Hurbanovo", force: "5%", fa: "Le faisan d'or de la Slovaquie : le sud du pays a ses trésors." },
  { nom: "Dreher", emoji: "🇭🇺", type: "Lager", origine: "Hongrie — Budapest", force: "5%", fa: "Antal Dreher a inventé la lager viennoise à Budapest : la famille règne toujours." },
  { nom: "Obolon", emoji: "🇺🇦", type: "Lager", origine: "Ukraine — Kiev", force: "4,7%", fa: "La bière du Dniepr : le fleuve donne l'eau, Kiev donne la mousse." },
  { nom: "Castle Lager", emoji: "🇿🇦", type: "Lager", origine: "Afrique du Sud — Johannesburg", force: "5%", fa: "La bière du braai (le barbecue sud-africain) : le château du goût." },
  { nom: "Tusker", emoji: "🐘", type: "Lager", origine: "Kenya — Nairobi", force: "4,2%", fa: "L'éléphant du Kenya : la savane se boit très fraîche." },
  { nom: "Erdinger Dunkel", emoji: "🇩🇪", type: "Dunkelweizen", origine: "Allemagne — Erding", force: "5,6%", fa: "La dunkle du froment : le pain grillé à la bavaroise." },
  { nom: "Founders KBS", emoji: "🇺🇸", type: "Stout au café", origine: "États-Unis — Michigan", force: "12%", fa: "Breakfast Stout vieilli en fûts de bourbon : « Kentucky Breakfast », le matin des champions." },
  { nom: "Founders Breakfast Stout", emoji: "🥞", type: "Stout au café", origine: "États-Unis — Michigan", force: "8,3%", fa: "Café et chocolat double crème : le petit-déjeuner officiel du Michigan." },
  { nom: "Great Lakes Edmund Fitzgerald", emoji: "⚓", type: "Porter", origine: "États-Unis — Cleveland", force: "6%", fa: "Nommée d'après le cargo qui a coulé dans le lac Érié : le porter des marins." },
  { nom: "Löwenbräu", emoji: "🍺", type: "Helles", origine: "Allemagne — Munich", force: "5,2%", fa: "Le lion brune de Munich : à l'Oktoberfest, le lion rugit dans les litre." },
  { nom: "Hacker-Pschorr", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "4,9%", fa: "Le « ami du peuple » : la brasserie des révolutions munichoises." },
  { nom: "Spaten", emoji: "🇩🇪", type: "Helles", origine: "Allemagne — Munich", force: "4,9%", fa: "Le « pie » de la brasserie : la première à faire de la publicité (1499... non, 1894)." },
  { nom: "Harvey's Tom Paine", emoji: "🇬🇧", type: "Old ale", origine: "Angleterre — Lewes", force: "6,5%", fa: "Nommée d'après le révolutionnaire de Lewes : la bière des droits de l'homme." },
  { nom: "Hoegaarden Grand Cru", emoji: "🇧🇪", type: "Blanche forte", origine: "Belgique — Hoegaarden", force: "8,5%", fa: "La blanche dopée au coriandre et au curaçao : la grande réserve du froment." },
  { nom: "St Bernardus Tripel", emoji: "🇧🇪", type: "Triple d'abbaye", origine: "Belgique — Watou", force: "8%", fa: "La triple du phénix de Watou : ronde, épicée, mousse de soie." },
  { nom: "Weihenstephaner Pils", emoji: "🇩🇪", type: "Pilsner", origine: "Allemagne — Freising", force: "5%", fa: "La pils des moines bavarois : quand l'ordre cistercien rencontre le houblon de Hallertau." },
  { nom: "Orval Grande Réserve", emoji: "🐟", type: "Trappiste vieillie", origine: "Belgique — Orval", force: "6,4%", fa: "L'Orval mise en réserve : les bouteilles numérotées partent en un clin d'œil." },
  { nom: "Cantillon Vigneronne", emoji: "🍇", type: "Lambic aux raisins", origine: "Belgique — Bruxelles", force: "5%", fa: "Des raisins muscat sur lambic : la brasserie rend hommage au vin, en silence." },
  { nom: "Grimbergen Rouge", emoji: "🇧🇪", type: "Bière fruitée ambrée", origine: "Belgique — Grimbergen", force: "6%", fa: "Le phénix se pare de rouge : des arômes de fruits rouges et de caramel." },
  { nom: "Samuel Smith Nut Brown Ale", emoji: "🌰", type: "Brown ale", origine: "Angleterre — Tadcaster", force: "5%", fa: "La brown aux noisettes du Yorkshire : douce comme un pub au coin du feu." },
];
// catalogue complet : A + B + C dans l'ordre d'origine
const BIERES_CULTES = [...BIERES_CULTES_A, ...BIERES_CULTES_B, ...BIERES_CULTES_C];
