// ---- Beer Runner — anecdotes EN, partie 4/5 ----
const BIERES_CULTES_EN_A = {
  "Westvleteren 12": "Brewed by label-shy monks: to buy it, book an appointment at the abbey itself.",
  "Westvleteren Blond": "The monks' small blond, sold only at the monastery gate.",
  "Westvleteren 8": "One of the three Westvleteren, every bit as rare as its sisters.",
  "Orval": "Legend says a trout returned a lost ring to the abbey fountain — that's her on the label.",
  "Petit Orval": "The small Orval, served only at the abbey's inn: the monks keep it for passing pilgrims.",
  "Rochefort 6": "The most discreet of the three Rochefort, a connoisseur favorite.",
  "Rochefort 8": "The perfect balance between the 6 and the 10, say the monks.",
  "Rochefort 10": "The numbers come from pre-war wort densities. Sip the 10 like a whisky.",
  "Rochefort Triple Extra": "The monks' limited edition: when it's there, grab it.",
  "Chimay Bleue": "The Grande Réserve: strong, spiced, built for cellar aging.",
  "Chimay Rouge": "The first Chimay in history, gentle and fruity.",
  "Chimay Blanche": "The 'Cinq Cents': crisp bitterness with a muscat finish.",
  "Chimay Dorée": "For decades it was reserved for the monks and their guests.",
  "Westmalle Tripel": "THE reference tripel: the whole world tries to copy it.",
  "Westmalle Dubbel": "The mother dubbel: it set the style for all abbey browns.",
  "Westmalle Extra": "The monks' own table beer, impossible to find in shops.",
  "Achel Blond": "Brewed near the Dutch border in the most discreet Trappist abbey.",
  "Achel Bruin": "A keeping brown with a light touch of toasted caramel.",
  "Leffe Blonde": "Born at Leffe abbey in 1152: monks brewed to fund the upkeep.",
  "Leffe Brune": "Soft and roasted, the Sunday-afternoon brown.",
  "Leffe Rituel 9°": "A Leffe that climbs: sip it slowly, no gulping.",
  "Grimbergen Blonde": "The phoenix on the label: the abbey burned down and was rebuilt many times.",
  "Grimbergen Optimo Bruno": "Grimbergen's 'beer of the scholars', a barrel of excellence.",
  "Maredsous 8": "The Benedictine abbey's brown, perfect with its namesake cheese.",
  "Maredsous 10": "The full-bodied one of the family — to share... or not.",
  "St Bernardus Abt 12": "Once brewed for the Westvleteren monks: the secular cousin of the 12.",
  "St Bernardus Wit": "A creamy traditional-style wit, lemon optional.",
  "St Bernardus Christmas Ale": "The Flemish Advent beer: spices, dates and a good fireplace.",
  "St Bernardus Grottenbier": "Designed to age in the region's marble caves.",
  "Affligem Blonde": "A thousand-year-old abbey beer with cappuccino-grade foam.",
  "Affligem Tripel": "A high-flying tripel inherited from the Affligem monks.",
  "Val-Dieu Triple": "The Val-Dieu abbey reopened its brewery in the year 2000.",
  "Val-Dieu Brune": "A keeping brown brewed with the abbey spring water.",
  "Tongerlo Tripel": "A tripel from the country's oldest canons' abbey.",
  "Floreffe Blonde": "The Floreffe canons were already brewing in the 12th century.",
  "Postel Blond": "The round taste of the monks of the Postel forest.",
  "Bornem Double": "A brown in the style of the old Lent fast beers.",
  "Ename Dubbel": "A brown from the vanished Ename abbey, resurrected by brewery.",
  "Saint-Feuillien Brune": "The Saint-Feuillien abbey has brewed in Hainaut since 1873.",
  "Steenbrugge Dubbel": "A brown from Saint-Peter's abbey in Steenbrugge, monks' recipe.",
  "Duvel": "A brewer tasted the first batch and shouted 'a real Duvel!' — a real devil.",
  "Duvel Tripel Hop": "Three fresh hops instead of one: the pentathlon version of the Devil.",
  "Chouffe": "The white-bearded gnome protects the brewery — and steals beers from tourists.",
  "La Chouffe Mc Chouffe": "A scotch ale brewed by Belgians with a Scottish gnome on the label.",
  "N'Ice Chouffe": "The winter Chouffe: spices and damsons, plus the gnome's beanie.",
  "Delirium Tremens": "The pink elephant on the bottle: here the delirium is in the name.",
  "Delirium Noël": "The festive version of the delirium: drink before seeing pink reindeer.",
  "Piraat": "10.5% of hearty hops: the jolly roger of Belgian beers.",
  "Gulden Draak": "The golden dragon: a third fermentation in the bottle, a keeping monster.",
  "Kasteel Rouge": "A brown steeped with cherries: the dessert you drink.",
  "Kasteel Donker": "The Ingelmunster castle brown, sweet as barley syrup.",
  "Ciney Blonde": "The Ciney blond with generous foam and polite bitterness.",
  "Ciney Brune": "The Condroz brown, caramel and barley cream.",
  "Brigand": "Named after the 1798 rebels: it runs its own rebellion.",
  "Lucifer": "The name says it all: golden, devilishly spiced, damnation guaranteed.",
  "Judas": "A kiss and a slap: sweetness first, alcohol after.",
  "Gouden Carolus Classic": "Emperor Charles Quint's beer, say the Mechelen brewers.",
  "Gouden Carolus Hopsinjoor": "Nine different hops: the crown is worn on the tongue too.",
  "Bush Ambrée": "The strongest of the classic Belgian beers: respect it, don't taunt it.",
  "Barbar": "A blond brewed with acacia honey: the bee does half the work.",
  "Verboden Vrucht": "The forbidden fruit: Adam and Eve on the label, the sin in the glass.",
  "Cuvée des Trolls": "Brewed with dried oranges: full mouth, light head.",
  "Satan Gold": "A 'beer of the gods': the marketing was already strong in 1988.",
  "Tripel Karmeliet": "Barley, wheat AND oats: the three-grain tripel, a crisp delight.",
  "Straffe Hendrik": "The 'strong Henri' of the Van Houcke family, in medieval Bruges.",
  "Brugse Zot Dubbel": "The 'fools of Bruges' mocked by Emperor Maximilian: the nickname stuck.",
  "Kwak": "The coachman's stirrup-cup glass hooks onto the bench. Strap yourself in.",
  "Poperings Hommelbier": "Hommel means hops in Flemish: you drink the hop capital of Belgium.",
  "Hommel Ale": "Brewed by the Van Eecke family, the other hop farm of the area.",
  "Lupulus": "Brewed with Ardennes spring water: hops rule here.",
  "Silly Saison": "The Hainaut farm saison, as told by the Silly brewery.",
  "Saison Dupont": "The world's reference saison, born to refresh the harvest crews.",
  "Avec les Bons Vœux": "Dupont's premium saison: the greetings card you drink.",
  "La Merveille": "A saison from the Blaugies farm brewery, by the hedgerows.",
  "Fantôme": "Dany Prignon brews unpredictable saisons: every cask is a surprise.",
  "Taras Boulba": "Nabokov on the label, fresh hops in the glass: 4.5% of poetry.",
  "Zinnebir": "The river Senne lends its name to this crisp amber.",
  "XX Bitter": "De Ranke made it for bitterness fanatics: harsh and proud.",
  "Guldenberg": "De Ranke's other gem: soft, golden, hoppy the old way.",
  "De Ranke Kriek": "Real cherries on lambic, no syrup: honest tartness.",
  "Wipers Times": "A tribute to the Great War trench newspaper, brewed English-style.",
  "Troubadour Mocha Stout": "A stout the Belgian way: cocoa and coffee, still packing heat.",
  "Bourgogne des Flandres": "A blend of lambic and sweet brown: Burgundy wine, beer version.",
  "Rodenbach": "Aged two years in oak: acidity and cherry, the Flanders signature.",
  "Rodenbach Vintage": "Single cask, vintage-dated: the grand cru of Flemish reds.",
  "Duchesse de Bourgogne": "Aged 18 months in oak: the duchess graces fine tables.",
  "Liefmans Goudenband": "So thick it was traditionally cut open with a knife.",
  "Liefmans Cuvée Brut": "Cherries steeped champagne-style: bubbles included.",
  "Cantillon Gueuze": "Fermented by the wild airborne yeasts of Brussels, in an open attic.",
  "Cantillon Kriek": "Two hundred grams of cherries per liter: fruit and acidity in a duel.",
  "Cantillon Rosé de Gambrinus": "Noble raspberry on one-year lambic: pink and biting.",
  "Cantillon Fou' Foune": "Roussillon apricots on lambic: the brewer's electric fairy.",
  "3 Fonteinen Oude Geuze": "A blend of one-, two- and three-year lambics, corked like champagne.",
  "3 Fontainen Schaarbeekse Kriek": "Brussels' small sour cherries, just like the old days.",
  "Boon Oude Geuze Mariage Parfait": "The 'perfect marriage': three years in the barrel before bottling.",
  "Boon Kriek": "The sweet-sour kriek of the Lembeek brewery-museum.",
  "Lindemans Gueuze": "The filtered, sweetened gueuze: the gateway to the lambic world.",
  "Lindemans Kriek": "The approachable kriek: perfect for converting skeptics.",
  "Lindemans Framboise": "Raspberry syrup or not, it still rests on real lambic.",
  "Mort Subite Oude Gueuze": "'Sudden death': the name of the Brussels café where it was drunk.",
  "Belle-Vue Gueuze": "The Sunday gueuze: soft, lemony, with fine foam.",
  "Oud Beersel Oude Geuze": "Counter-style gueuze, straight from the Flemish schoolbook.",
  "Tilquin Gueuze": "The last independent gueuze blender: he buys the lambic, not the brewery.",
  "Hanssens Oude Gueuze": "One of the sourest in the country: teeth tingle, hearts flutter.",
  "Girardin Gueuze": "The giraffe on the label: a rustic Walloon Brabant gueuze.",
  "De Cam Oude Geuze": "Blended at the farm, on the high plateaus of the Pajottenland.",
  "Hoegaarden": "The wit with coriander and orange peel: invented by Pierre Celis.",
  "Blanche de Namur": "Born from the legend of the 'Blonde of Namur', a 15th-century princess.",
  "Brugs Tarwebier": "The Bruges wheat beer: refreshing after the Minnewater.",
  "Weihenstephaner": "The world's oldest working brewery (1040): it survived everything.",
  "Weihenstephaner Vitus": "A wheat doppelbock: banana and clove, supercharged.",
  "Schneider Weisse Tap 6": "Georg Schneider has kept Munich wheat alive since 1872.",
  "Aventinus": "Bavaria's oldest wheat doppelbock: complex and velvety.",
  "Schneider Edel Weisse": "The tonic, spicy version of the Schneider wheat.",
  "Erdinger Weissbier": "The 'champion's' weissbier: sport and beer, contract signed.",
  "Franziskaner": "The Franciscan monk on the label: central Munich's wheat beer.",
  "Maisel Weisse": "Bayreuth's 'Weisse pearl': fruity, fleshy, generous.",
  "Ayinger Bräu Weisse": "Brewed in the village of Aying: the foam is actual cream.",
  "Schöfferhofer Weizen": "The Mainz wheat beer you find everywhere and always re-order.",
  "Augustiner Helles": "Munich's favorite: gravity-poured straight from the tap.",
  "Augustiner Edelstoff": "'Noble stuff': the Augustinian brewery's treasure, bottles only.",
  "Augustiner Dunkel": "The Munich brown par excellence: toasted bread and caramel.",
  "Tegernseer Spezial": "The former Tegernsee abbey brewery: the lake, the hills, the beer.",
  "Jever Pils": "The north's 'pils with bite': dry, herbal, sharp as a sea breeze.",
  "Warsteiner": "The 'queen of pils' according to the ads: Germany's everywhere-bomb.",
  "Radeberger": "East Germans' favorite pils, born under Bismarck.",
  "Bitburger": "'Bitte ein Bit': Germany's most quotable slogan.",
  "Veltins": "The Sauerland pils, always served ice cold.",
  "Flensburger": "The swing-top 'plop': you hear it before you drink it.",
  "Rothaus Tannenzäpfle": "The 'little pine cone' from the Black Forest, land of fir trees.",
  "Kneitinger Pils": "The Regensburg pils, Bavarian purists' favorite.",
  "Hofbräu Original": "The Duke of Bavaria's brewery: served in one-liter mugs.",
  "Löwenbräu Original": "The Munich lion has brewed since 1383: the Oktoberfest beer.",
  "Paulaner Münchner Hell": "The Paulaner monks brewed to survive: their hell is holy.",
  "Paulaner Salvator": "The 'Savior': monks fasted on it, hence the name. Holy excuse.",
  "Ayinger Celebrator": "The goat medal on the label: the reference doppelbock.",
  "Andechser Doppelbock": "Brewed by Benedictines on the Andechs hill: a tasty pilgrimage.",
  "Korbinian": "Named after Saint Korbinian, the bishop with the bear: legend in a bottle.",
  "König Ludwig Weiss": "The royal brewery by Hohenschwangau, facing Louis II's castle.",
  "EKU 28": "Once the strongest beer in the world: sipped like a digestif.",
  "Kulmbacher Eisbock": "The legend: a cask left outside froze, ice removed, alcohol concentrated.",
  "Schneider Aventinus Eisbock": "Aventinus partially frozen: banana, chocolate and dark fruit.",
  "Einbecker Mai-Ur-Bock": "Einbeck is the mother of bocks: its name gave 'Bock' to Bavaria.",
  "Schlenkerla Märzen": "Beechwood-smoked malt: the ham of beers, Bamberg loves it.",
  "Schlenkerla Weizen": "A smoked wheat: bakery and bar counter in one glass.",
  "Spezial Rauchbier": "Bamberg's other smoke, gentler: the town counts two schools.",
  "Diebels Alt": "The 'thief': the reference alt, red-brown and dry.",
  "Uerige Alt": "The 'deliciously sour' Uerige alt: tiny glasses at the counter.",
  "Schumacher Alt": "The oldest alt house (1838): you drink standing, packed, happy.",
  "Füchschen Alt": "The little fox of old Düsseldorf: bitter and rustic.",
  "Gaffel Kölsch": "The reference thistle-glass kölsch: while the glass is full, they refill.",
  "Reissdorf Kölsch": "Cologne's most-drunk kölsch: 20cl at a time, sweet madness.",
  "Früh Kölsch": "The kölsch by the old harbor next to the cathedral: a pilgrimage.",
  "Mühlen Kölsch": "Brewed at the city mill: the most confidential kölsch.",
  "Berliner Kindl Weisse": "The Prussian kings' beer, so sour it takes a shot of syrup.",
  "Pinkus Alt": "The organic brewery before its time: real taste since 1816.",
  "Weltenburger Barock Dunkel": "The abbey claims the world's oldest monastery brewery title.",
  "Altbairisch Dunkel": "Old Bavaria's brown: rye bread, prune, softness.",
  "Köstritzer Schwarzbier": "Goethe's black beer: the poet sipped this 'black velvet' while writing.",
  "Goslarer Gose": "Sour, salty, coriander-spiced: forgotten by the Middle Ages, then revived.",
  "Kuchlbauer Weisse": "Its golden tower was designed by Hundertwasser: art with your weissbier.",
  "Neumarkter Lammsbräu": "Germany's organic pioneer: the beer of respect, since 1979.",
  "Beck's": "The green bottle only leaves Bremen for export: locals drink it on draft.",
  "St. Georgen Bräu Kellerbier": "Brewed 'on the lees' in the shade of the cellars: perfect cellar beer.",
  "Fischer Tradition": "The keeping beer: brewed in winter, aged for months to last the summer.",
  "Adelscott": "Peat-smoked malt, whisky-style: Alsace doing Scotland.",
  "Pelforth Blonde": "'Pel my god': the Pelforth pelican conquered French bistro counters.",
  "Pelforth Brune": "The 60s brown: fathers still ask for it at the counter.",
  "3 Monts": "The North's keeper: brewed in the Flemish heights, built to age.",
  "La Goudale": "Conceived to pay off 'goudale' debts: the counts of Flanders' beer.",
  "Jenlain Ambrée": "The Northern beer that relaunched French brewing in 1974.",
  "La Choulette Ambrée": "Brewed in a former Northern farmhouse brewery: the return of taste.",
  "Ch'ti Blonde": "The Ch'ti in beer form: welcome to the North's bistro.",
  "Ch'ti Rousse": "The miners' red: coal in the glass, but nicer.",
  "Mont des Cats": "France's only Trappist: once brewed at the abbey, revived in 2016.",
  "Bière du Démon": "12% alcohol: the French demon — respect it before whistling at it.",
  "Cervoise Lancelot": "The Gauls' cervoise, brewed in a Breton castle's hearth.",
  "Telenn Du": "Breton buckwheat: the crêpe you can drink.",
  "Britt Blonde": "The Breton's apéritif: Armorican wheat.",
  "Britt Rousse": "The Breton red: caramel and demi-sel butter (almost).",
  "Meteor Pils": "Alsace's independent: the last big family brewery.",
};
